- src/page-overview/OverviewPage.tsx
- src/page-overview/assets/data-forms.js
- src/page-overview/assets/init.js
This implements an auto-suggest and auto-complete for the state name input (alternative to clicking on the map). Per mocks it just suggests the first alphabetical match, if there is any, and commits the suggestion when the user presses Enter or Tab.
> Autocomplete state name

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/general_task.md
- .github/pull_request_template.md
Pull request and issue templates are required for Recidiviz SOC-2 compliance. This adds our standard template set (slightly modified) for the new repository.
> Adds pull request and issue templates for security compliance.

- src/impact-dashboard/EpidemicModelContext.tsx
- src/impact-dashboard/ImpactDashboard.tsx
- src/impact-dashboard/ImpactDashboardContainer.tsx
- src/impact-dashboard/index.tsx
This creates a shared datastore for both the input forms and the curve charts, initialized to match all the input fields in our latest mocks. We are probably going to want to add some more actions later (at the least, probably one to populate the store with state & county level data from an external data source, once we have one set up) but this should get us started for now.
Also I know some TypeScript now? 😎 
> React context for model input data

- src/entry-point-client/PageList.tsx
Whoops, gave the page the wrong title.
> Fix "Get Involved" page title

- src/impact-dashboard/EpidemicModelContext.tsx
- src/infection-model/index.tsx
- src/infection-model/seir.tsx
This brings the web model up to feature completeness for initial launch. This includes full age-bracket data for both population and confirmed cases, and incorporation of facility occupancy rates and housing types. Outputs have been validated against the latest spreadsheet and are accurate to within 0.8%.
This does break the original map-and-slider UI; our plan is to remove it from the launch UI and bring it back later so I just did the bare minimum to get Typescript to stop yelling at me about it. A subsequent PR will clean that up so I don't think we should fuss about it for now. 
> Epidemic model updates

- src/entry-point-client/PageList.tsx
This leads to a redirect to the login form from the base url, as per the spec and confirmation with @sychang. Tested the login, logout, and registration flows with this change locally and everything appears to work as expected.
> Hides the landing path behind auth

- src/design-system/InputLabelAndHelp.tsx
- src/design-system/InputSelect.tsx
- src/design-system/InputText.tsx
- src/design-system/InputTextNumeric.tsx
- src/impact-dashboard/ImpactDashboard.tsx
This fixes some of the spacing issues with the form inputs, including making them responsive to smaller screens. Ultimately I had to abandon the table-based layout in favor of flex to make this work. 
> Improve spacing and responsiveness in form

- src/entry-point-client/index.tsx
Struggling against the configuration in now.sh, so I'm breaking some rules here...
> Making no-op commit to attempt to trigger production deploy.

- src/impact-dashboard/ImpactDashboard.tsx
- src/page-overview/OverviewPage.tsx
Minor copy updates per:  https://github.com/Recidiviz/covid19-dashboard/projects/1#card-36002101
> Minor Copy Updates

- .github/pull_request_template.md
> Updates the PR template to include related issues.

- src/entry-point-client/PageList.tsx
- src/page-multi-facility/MultiFacilityPage.tsx
Blank multi-facility page with SiteHeader and route (input requested on route naming). Intention is to use this to build/test components that are being developed for this page.
In support of issue #93 
> multi-facility page with SiteHeader and route

- src/design-system/Colors.tsx
- src/design-system/InputToggle.tsx
- src/entry-point-client/PageList.tsx
- src/page-multi-facility/MultiFacilityPage.tsx
> Adds a `InputToggle` component that takes `toggled` and `onChange` props. 
This is my first PR and my first time working with styled-components and TypeScript, so I appreciate any and all feedback! Thank you for including me in this project, I'm looking forward to working together. 
The first commit is from @jovergaag and adds a multi-facility page so that we can stage the components. 
Closes [#98]
Part of #93 
> Add toggle component for  multi-facility page

- src/design-system/Colors.tsx
- src/design-system/HelpButtonWithTooltip.tsx
- src/design-system/InputLabelAndHelp.tsx
- src/design-system/InputToggle.tsx
- src/design-system/TextLabel.tsx
- src/design-system/Tooltip.tsx
- src/page-multi-facility/MultiFacilityPage.tsx
- src/page-multi-facility/ToggleRow.tsx
-Adds ToggleRow(s) to the multi-facility page.
-Adds muted styling to HelpButtonWithTooltip
-Adds InputToggle to the rows and adjusts toggle styling
This is also my first time working with Typescript and styled components so feel free to give any feedback!
issue #99 
> Adds 'Participation' rows with Help button, Tooltip and Toggle - MultiFacilityPage

- index.html
Adds basic Google Analytics integration. May consider Segment integration after our next release so we can add in our destinations but this suffices for now.
Tested locally that the integration successfully reports to G.A. (when trackers are permitted :) and tested that the build still succeeds and includes the tracking script in its output.
Closes #75 
> Adds Google Analytics integration.

- src/page-multi-facility/MultiFacilityPage.tsx
- src/page-multi-facility/ProjectionsHeader.tsx
- src/page-multi-facility/ScenarioSidebar.tsx
"Merging" the work I've already done with frontend the work that is in progress.
I had a bit of a head start on doing some o the layout and styles for the multi-facility page.  Now that @daschi and @jovergaag are helping out as well, I wanted to make sure that I got the work I had already completed "merged" in so that we don't step on each others' toes.
Closes []
> Multi-Facility Page Layout Markup

- src/database/index.tsx
Adding in the ability to create a new baseline scenario.  I've tested this locally to confirm that the code correctly returns the user's existing baseline scenario or creates a new one if a baseline does not yet exist.
Closes #121
> Add the Ability to Create a Baseline Scenario for a Logged In User

- src/database/index.tsx
- src/design-system/ModalDialog.tsx
- src/design-system/ModalTitle.tsx
- src/page-multi-facility/CreateBaselineScenarioPage.tsx
- src/page-multi-facility/MultiFacilityImpactDashboard.tsx
- src/page-multi-facility/MultiFacilityPage.tsx
> Adds a Welcome modal when a logged in user accesses the multi facility page and they do not yet have a baseline scenario. 
TODO: 
Closes #123 
> Add the empty state multi-facility page

- src/database/__tests__/testcases.tsx
- src/database/index.tsx
- src/impact-dashboard/EpidemicModelContext.tsx
- src/page-multi-facility/types.tsx
* Adding the ability to save and update a facility to Firestore.
Closes #127
> Add the Ability to Save Facilities

- src/entry-point-client/App.tsx
- src/page-multi-facility/FacilityContext.tsx
- src/page-multi-facility/FacilityPage.tsx
- src/page-multi-facility/FacilityRow.tsx
- src/page-multi-facility/MultiFacilityImpactDashboard.tsx
- src/page-multi-facility/types.tsx
Loads the Facility page when a Facility Row on the Multifacility page is clicked
Closes #126
> Loading the Facility Page when a Facility Row is Clicked

- src/database/index.tsx
- src/page-multi-facility/FacilityInputForm.tsx
- src/page-multi-facility/FacilityPage.tsx
Updating the facility page to allow for persistence.  This required a decent chunk of refactoring to get things in a functional state.
Closes #142
> Wire Persistence to Facility Details Page

- src/database/index.tsx
- src/page-multi-facility/MultiFacilityImpactDashboard.tsx
- src/page-multi-facility/MultiFacilityPage.tsx
- src/page-multi-facility/ScenarioSidebar.tsx
- src/page-multi-facility/ToggleRow.tsx
- src/page-multi-facility/types.tsx
> Pass in the baseline scenario to the Scenario Sidebar component. I'm opening this as a WIP and having turned off the linter requirements so that it can be picked up by someone else later if needed. 
TODO: 
Question - What data should go in the description below the header?
Closes #131
> Start wiring up the scenario sidebar

- src/page-multi-facility/FacilityRow.tsx
* Adds the ability to delete a facility from a given Scenario (currently just the Baseline)
#147 
> Deleting a Facility

- src/design-system/Tooltip.tsx
- src/page-multi-facility/CreateBaselineScenarioPage.tsx
- src/page-multi-facility/ScenarioSidebar.tsx
This finalizes all copy prior to the release of multi-facility support.
Related to #70 
> Multi-facility copy updates

- src/infection-model/seir.tsx
Distributes initial cases proportionally across various states of sickness and recovery, to match Excel model. Outputs verified against spreadsheet for accuracy.
Closes #173 
> distribute initial cases across more compartments

- src/design-system/Colors.tsx
- src/impact-dashboard/ImpactProjectionTable.tsx
> Update the text content, font size, style and color for the outputs table on the edit facility view. @cawarren Just would like to confirm the font-sizes for the table headings as they seemt o be very small (i.e. "Impacted projections" - 9px and "Total incarcerated population" - 10px) 
Part of #167
> Edit Facility View - Update table text font / color to reflect mocks

- src/page-multi-facility/types.tsx
Removing the duplicate `TimeStamp` type and favoring `Timestamp` since "Timestamp" is one word.
N/A
> Removing Duplicate TimeStamp Type

- src/design-system/Colors.tsx
- src/design-system/PromoBoxWithButton.tsx
- src/page-multi-facility/FacilityRow.tsx
- src/page-multi-facility/MultiFacilityImpactDashboard.tsx
- src/page-multi-facility/ProjectionsHeader.tsx
- src/page-multi-facility/ScenarioSidebar.tsx
- src/page-multi-facility/ToggleRow.tsx
- src/site-header/SiteHeader.tsx
1. change font, color, weight and size.
2. ensure border color consistency on dashboard
Part #167 
> style facility graph headers

- src/design-system/Colors.tsx
- src/page-multi-facility/CreateBaselineScenarioPage.tsx
> Reduces the font size for the text in the welcome modal from 18px to 16px.
Part of #167 
> Set welcome font size to 16px

- src/design-system/InputDescription.tsx
- src/design-system/InputNameWithIcon.tsx
- src/page-multi-facility/ScenarioSidebar.tsx
Bug fix for issue #220 
Closes #220
> Persist Changes to Name and Description in the Scenario Sidebar

- .babelrc.json
- README.md
- package.json
- setupTests.tsx
- src/__mocks__/svgMock.tsx
- src/database/__tests__/testcases.tsx
- src/design-system/InputDescription.tsx
- src/design-system/InputNameWithIcon.tsx
- src/design-system/__tests__/InputToggle.test.tsx
- src/page-multi-facility/ScenarioSidebar.tsx
- yarn.lock
A bug fix release following from today's previous release: ensuring that scenario and facility renames are persisted as expected.
Verified this diff is a no-op on master.
> Bug fix release: April 24, 2020

- src/entry-point-client/PageList.tsx
- src/page-response-impact/ResponseImpactDashboard.tsx
- src/page-response-impact/ResponseImpactPage.tsx
Creates the `ResponseImpactPage` and route '/impact'
Closes #233 
> ResponseImpactPage and route

- src/design-system/PageColumn.tsx
- src/design-system/PageLayoutColumns.tsx
- src/page-multi-facility/FacilityInputForm.tsx
- src/page-multi-facility/FacilityPage.tsx
- src/page-response-impact/ResponseImpactDashboard.tsx
> This adds the basic page layout with the two columns and styles for the headings. I added some placeholder divs for now for the charts, content, and placeholder text for the dynamic headers. 
Closes #236
> [Excalibur] Create basic page layout, headings and styles

- src/design-system/InputToggle.tsx
- yarn.lock
- Update toggle width and height
Before:
After:
Part of #167
> Update toggle width and height

- src/design-system/TextLabel.tsx
Follow-on to https://github.com/Recidiviz/covid19-dashboard/pull/241
Addresses some of: #167
No visual change 
> Use Colors variable to be DRY

- src/database/index.tsx
- src/database/type-transforms.tsx
- src/infection-model/rt.tsx
- src/page-multi-facility/FacilityRow.tsx
- src/page-multi-facility/ScenarioSidebar.tsx
- src/page-multi-facility/types.tsx
* Populating our Domain objects with consistent JavaScript Dates so that client code can be written consistently without worrying about dealing with multiple date-like types.
Closes #144 #262
> Populate Domain Objects with Consistent Types

- src/locale-data-context/LocaleDataContext.tsx
add Column J from Google Spreadsheet into locale context. Only appears on `state.total` currently, since counties do not have a value for this column.
necessary for Excalibur work.
> add prison pop (mainly used for states)

- backend/firestore.rules
- src/database/index.tsx
Adding support for deleting scenarios
Closes #285 
Verified that delete a scenario removes all child documents ✅ 
> Add Support for Deleting Scenarios

- backend/python-functions/helpers.py
This should help us better debug Rt issues, including anything unexpected found in the wild. Verified against the development function, you can see example output in the logs for `calculate_rt_development` in Firebase.
Closes #258 
> log inputs and responses in cloud function wrapper

- src/design-system/InputDescription.tsx
- src/design-system/InputNameWithIcon.tsx
- src/design-system/InputText.tsx
- src/page-multi-facility/FacilityInputForm.tsx
- src/page-multi-facility/FacilityRow.tsx
Some Prettier violations seem to have snuck into `master`, this fixes them.
none
> fix lint errors

- src/design-system/HelpButtonWithTooltip.tsx
- src/design-system/InputLabelAndHelp.tsx
- src/design-system/TextLabel.tsx
- src/design-system/Tooltip.tsx
- src/page-multi-facility/MultiFacilityImpactDashboard.tsx
- src/page-multi-facility/ProjectionsLegend.tsx
- src/page-multi-facility/ScenarioSidebar.tsx
- src/page-multi-facility/ToggleRow.tsx
Fixes a grab bag of UI issues in the scenario sidebar and facility list header. As far as I was able to tell, the style changes to underlying components don't break anything else.
Closes #319 
> Scenario UI tweaks

- src/rt-timeseries/RtTimeseries.tsx
What it says on the tin:
Closes #322 
> add tooltip to Rt timeseries title

- src/feature-flags/featureFlags.tsx
Not ready to deploy this feature to production yet. The flag does not come from an environment variable so this code change is required.
none
> toggle off rate of spread flag for release

- src/impact-dashboard/EpidemicModelContext.tsx
- src/page-response-impact/ResponseImpactDashboard.tsx
- src/page-response-impact/ValidDataWrapper.tsx
Validates response impact data to ensure that all facilities have the same `systemType` and `stateCode`. Also verifies that each facility has staff population and total incarcerated population greater than zero.
Displays an appropriate error message with invalid data.
Closes #266 
> [Excalibur] Validate response impact data

- src/impact-dashboard/CurveChart.tsx
- src/impact-dashboard/CurveChartContainer.tsx
- src/impact-dashboard/EpidemicModelContext.tsx
- src/locale-data-context/LocaleDataContext.tsx
- src/page-multi-facility/FacilityInputForm.tsx
- src/page-multi-facility/FacilityRow.tsx
- src/page-multi-facility/ScenarioSidebar.tsx
- src/page-response-impact/ResponseImpactDashboard.tsx
- src/page-response-impact/ValidDataWrapper.tsx
- src/page-response-impact/responseChartData.tsx
A bug fix release that fixes a typo in new promo text, resolves a bug leading to inaccurate observedAt timestamps in some cases, and removes hospital beds lines from facility row graphs, which distort their epidemic curves in the compressed vertical space.
Confirmed that this PR pointed against master is a no-op.
> New Release: May 7, 2020

- src/feature-flags/featureFlags.tsx
CC @macfarlandian 
Related to #354 
> Enables the Rate of Spread tab for production usage.

- .env-example
- src/feature-flags/featureFlags.tsx
- src/hooks/useFacilitiesRtData.tsx
- src/page-multi-facility/FacilityInputForm.tsx
- src/page-multi-facility/FacilityProjections.tsx
- src/page-multi-facility/FacilityRow.tsx
- src/page-multi-facility/MultiFacilityImpactDashboard.tsx
- src/page-response-impact/ResponseImpactDashboard.tsx
- src/page-response-impact/RtSummaryStats.tsx
Just some Friday afternoon housekeeping ... this feature has been out for a week, the flag is no longer needed. The curve functions still need the fallback behavior in some cases so that has been preserved. (also fixed a tangentially related TODO in Rt-land while I was in there, to use the new helper function for getting the most recent Rt value)
Closes #315 
> Remove feature flag for Rt

- src/design-system/InputName.tsx
- src/page-multi-facility/FacilityInputForm.tsx
- src/page-multi-facility/ScenarioSidebar.tsx
* Removing the Folder Icon coupling from the InputName in order to provide more UI flexibility in where and how we place this folder icon.  This is particularly relevant for the Scenario Library which needs to be triggered by the folder icon.
Closes #350
> Remove Icon Coupling from the InputNameWithIcon Component

- src/page-response-impact/ResponseImpactDashboard.tsx
IS:
Closes `P2: Change below copy to “Rate of spread, R(t), for modelled facilities` from https://docs.google.com/document/d/1_jbpbsObUWkakyitmuIMaNKhq1YVU_fpo4j06ip8ets/edit#
> [Excalibur] Update copy

- src/page-response-impact/PopulationReduction.tsx
- src/page-response-impact/ResponseImpactDashboard.tsx
- src/page-response-impact/styles.tsx
style new UI for population change
accumulate current population from facilities[]
add original population
some style cleanup for the page
Closes #298
> Population comparison UI component

- backend/python-functions/realtime_rt.py
- backend/python-functions/test.py
Remove the threshold check on day-over-day case increases that would trigger an error if it was not met. 
Change was deployed to the dev function and demonstrated no regression on my available test data.
Closes #374 
> Remove Rt threshold

- gatsby-config.js
- package.json
- yarn.lock
Adds Segment integration to the app. We will use this to integrate with other analytic services, such as Fullstory. Tested this locally with `yarn build && yarn serve`, since `yarn dev` does not apparently invoke all Gatsby plugins.
> Add Segment integration

- src/page-response-impact/ImpactMetricCard.tsx
Make the design more responsive
IS:
Part of: https://github.com/Recidiviz/covid19-dashboard/issues/360
> [Excalibur] Hide icon on small screen widths

- src/page-response-impact/BaselinePopulationModal/index.tsx
> Update Impact modal text
**Before**: A report will be generated to compare the current projected impact of COVID-19 on your system against the model’s original assumptions prior to any actions taken. For a complete report, ensure all facilities in your system are modelled, even if some facilities do not currently have confirmed cases.
**After**: This tool produces a report summarizing the impact of your interventions on the spread of Covid-19 in your facilities. To ensure accuracy, we recommend ensuring that all facilities in your system have been modeled with up-to-date data, even facilities which never had a confirmed case.
Closes [#349 ]
> Update Impact modal text

- src/database/index.tsx
- src/design-system/HelpButtonWithTooltip.tsx
- src/design-system/InputDate.tsx
- src/design-system/ModalDialog.tsx
- src/design-system/PageColumn.tsx
- src/design-system/Tooltip.tsx
- src/impact-dashboard/ImpactProjectionTableContainer.tsx
- src/infection-model/index.tsx
- src/infection-model/rt.tsx
- src/page-response-impact/BaselinePopulationModal/BaselinePopulationForm.tsx
- src/page-response-impact/BaselinePopulationModal/index.tsx
- src/page-response-impact/PopulationImpactMetrics.tsx
- src/page-response-impact/PopulationReduction.tsx
- src/page-response-impact/ReducingR0ImpactMetrics.tsx
- src/page-response-impact/ResponseImpactDashboard.tsx
- src/page-response-impact/responseChartData.tsx
- src/page-response-impact/utils/ResponseImpactCardStateUtils.tsx
- src/page-response-impact/utils/numberUtils.tsx
This release launches the new "Excalibur" feature - automatic impact tracking. This includes a new `/impact` route, reachable via a button on the Scenario Details page, which provides visualizations and summary stats describing the impact your policy and practice changes have had on key epidemic, public health, and public safety metrics within your jurisdiction.
Performed some local manual testing on this branch and confirmed that issuing this PR against master is a no-op.
> Production Release: May 12, 2020

- src/page-response-impact/ImpactMetricCard.tsx
- src/page-response-impact/ResponseImpactDashboard.tsx
- src/page-response-impact/styles.tsx
* Adjust layout and styling of /impact
* Change font to sans-serif (I've gone with Poppins, sans-serif whenever this comment is mentioned)
~~👉 There is a TS error in here that I'm stuck on for today, not sure why it's there yet, cause I didn't change any JS. Let me know or will bring up @ standup!~~
Part of [Excalibur UI polish Google doc](https://docs.google.com/document/d/1_jbpbsObUWkakyitmuIMaNKhq1YVU_fpo4j06ip8ets/edit)
> [Excalibur] Design tweaks to /impact page

- .env-example
- src/feature-flags/featureFlags.tsx
- src/page-multi-facility/ScenarioSidebar.tsx
> Remove Feature Flag for the Scenario Library

- src/page-multi-facility/ScenarioSidebar.tsx
Make generate impact report button available on all scenarios.
Closes #406 
> [Excalibur] Show generate impact report button for all scenarios

- .env-example
- backend/python-functions/realtime_rt.py
- backend/python-functions/test.py
- src/constants/dispatchEvents.tsx
- src/design-system/InputDate.tsx
- src/design-system/Loading.tsx
- src/design-system/Modal.tsx
- src/design-system/ModalDialog.tsx
- src/feature-flags/featureFlags.tsx
- src/hooks/UseComponentToggleVisible.tsx
- src/hooks/useFacilitiesRtData.tsx
- src/hooks/useFacilityModelVersions.tsx
- src/impact-dashboard/CurveChartContainer.tsx
- src/impact-dashboard/EpidemicModelContext.tsx
- src/impact-dashboard/FacilityInformation.tsx
- src/infection-model/rt.tsx
- src/page-multi-facility/AddCasesModal.tsx
- src/page-multi-facility/FacilityContext.tsx
- src/page-multi-facility/FacilityInputForm.tsx
- src/page-multi-facility/FacilityRow.tsx
- src/page-multi-facility/ScenarioLibraryModal.tsx
- src/page-multi-facility/ScenarioSidebar.tsx
- src/page-multi-facility/types.tsx
- src/page-response-impact/ImpactMetricCard.tsx
- src/page-response-impact/ResponseImpactDashboard.tsx
- src/page-response-impact/RtSummaryStats.tsx
- src/page-response-impact/styles.tsx
This release includes improvements to the add cases modal to show which days have historical case observations, the ability to generate impact reports for non-baseline scenarios, the ability to delete non-baseline scenarios, R(t) calculation improvements, and a variety of UI tweaks.
Confirmed that this PR issued against master is a no-op.
> Production Release: May 15, 2020

- src/page-multi-facility/AddCasesModal.tsx
- src/page-multi-facility/FacilityRow.tsx
- src/page-multi-facility/ProjectionsHeader.tsx
Add residents number to multi facility page's table for each facility row. 
Plus update name at top of modal.
Closes #396
> add residents number to multi facility view

- src/page-multi-facility/CreateBaselineScenarioPage.tsx
Update copy in welcome modal (remove inaccurate reference to unfinished feature).
Closes #448
> update copy on welcome modal

- src/impact-dashboard/CurveChart.tsx
- src/page-about/AboutPage.tsx
- src/pages/about.tsx
- src/site-header/SiteHeader.tsx
> Re-add updated about page
Closes #77
> #77 Re-add updated about page

- src/database/type-transforms.tsx
- src/page-response-impact/BaselinePopulationModal/BaselinePopulationForm.tsx
- src/page-response-impact/BaselinePopulationModal/index.tsx
- src/page-response-impact/ResponseImpactDashboard.tsx
- src/page-response-impact/hooks/useSystemWideData.tsx
- src/page-response-impact/responseChartData.tsx
WAS:
IS:
---
~~Question: @daschi Serena mentioned something about different behavior the second time a user generates a report, but from looking at the code and clicking around, I'm not sure what she meant?~~ 
Was mentioned at standup then pinged @sychang when was looking for new task!
> [Excalibur] Change default date

- src/database/type-transforms.tsx
- src/page-response-impact/ResponseImpactDashboard.tsx
This releases includes a bug fix impacting scenarios that did not receive any data updates in an extended period of time, as well as a product-request copy change.
Confirmed that this PR issued against master is a no-op.
> Production Release: May 21, 2020

- tsconfig.json
Makes `tsc` faster using the `incremental` option!
TS blog post that introduced this option: https://devblogs.microsoft.com/typescript/announcing-typescript-3-4-rc/
**Impact**
Since we run `tsc` before creating each commit, this significantly reduces the time it takes to commit. How significantly?
Before
```
$ yarn tsc
✨  Done in 14.54s.
```
After, first run
```
$ yarn tsc
✨  Done in 15.53s.
```
After, subsequent runs
```
$ yarn tsc
✨  Done in 4.66s.
```
This change doesn't speed up CI builds, since each build is fresh, or `yarn dev`, since I think it's already incremental using other methods.
None
> Turn on ts incremental compile to make it faster to commit

- src/page-multi-facility/ScenarioLibraryModal.tsx
- src/page-multi-facility/ScenarioSidebar.tsx
* Change button font
* Fix styling of scenario sidebar header
* Now, names with single or multiple lines are spaced evenly from the folder on the LHS
* Fix typo
Use: https://github.com/Recidiviz/covid19-dashboard/pull/471/files?w=1
WAS:
IS (gif):
---
Question: I wanted to do this in a more "React way" but couldn't get that to work, take a look at that approach here in case you see something I can fix? https://github.com/Recidiviz/covid19-dashboard/compare/amy/merlin-ui-polish-q?expand=1
Closes part of https://github.com/Recidiviz/covid19-dashboard/issues/372, Google doc
> Merlin UI polish

- backend/firestore.rules
- src/database/index.tsx
This work includes:
* Investigating Security Rule Updates to Limit Potential Data Leakage from the User Collection
* Creating an addScenarioUser Function to Add a User to a Scenario
* Creating a getScenarioUsers Function to Retrieve a List of Users who can Access a Scenario
* Creating a removeScenarioUser Function to Remove a User from a Scenario
* Updating the getScenarios Function to Consider the viewer Role Type
Closes #461 #437 #436 #438 #440
> Scenario Sharing DB Functionality

- src/design-system/InputName.tsx
- src/design-system/PageColumn.tsx
- src/impact-dashboard/ChartArea.tsx
- src/page-multi-facility/FacilityInputForm.tsx
- src/page-multi-facility/FacilityPage.tsx
- src/site-header/SiteHeader.tsx
WAS:
IS:
Closes part of #372, Google doc
> Merlin UI polish: /facility page layout

- .eslintrc.json
- src/database/index.tsx
- src/page-multi-facility/ScenarioLibraryModal.tsx
Update the Scenario Library to Show All Scenarios Accessible by a User
**Before:**
**After:**
Closes #441
> #441 update Scenario Library modal

- backend/python-functions/main.py
Remove import of `flask.json`
> Description here
The import is unused, so isn't necessary.
Closes [#XXXX]
> Remove unused import.

- src/rt-timeseries/RtTimeseriesContainer.tsx
There is new error handling for R(t)
IS:
Closes: update from @sychang 
> Update R(t) empty state copy

- backend/python-functions/main.py
- src/database/index.tsx
- src/design-system/EditInPlace.tsx
- src/design-system/PopUpMenu.tsx
- src/design-system/Toast.tsx
- src/impact-dashboard/EpidemicModelContext.tsx
- src/infection-model/__tests__/validateCumulativeCases.test.tsx
- src/infection-model/validators.tsx
- src/page-multi-facility/FacilityInputForm.tsx
- src/rt-timeseries/RtTimeseriesContainer.tsx
This release includes a bug fix to avoid out-of-order processing of observed data points. It also includes a few small UI fixes.
Confirmed this PR issued against master is a no-op.
> Production release: June 2, 2020

- src/page-about/AboutPage.tsx
- src/page-multi-facility/AddCasesModal/AddCasesModalContent.tsx
- src/page-multi-facility/AddCasesModal/index.tsx
- Add Scenario Sharing guide to About page
- Change title/add some description to "Add/Update Cases" modal
Part of #372
> Add Scenario Sharing guide to About page

- src/database/index.tsx
- src/design-system/InputTextArea.tsx
- src/design-system/ModalDialog.tsx
- src/design-system/icons/ic_add_square.svg
- src/page-multi-facility/ScenarioLibraryModal.tsx
- src/scenario-create-new/CreateNewScenarioModal.tsx
Adds a form to the Scenario Library to allow for creating a new, blank Scenario
Closes #368 
> Allow Adding a New Scenario in the Scenario Library View

- src/database/index.tsx
- src/hooks/useCurrentUserEmail.tsx
- src/scenario-share/ScenarioShareModal.tsx
Raise error if current user tries to share their scenario with their self.
Closes #536
> raise error if currentUser submit to share scenario

- src/page-multi-facility/ReadOnlyScenarioBanner.tsx
- src/site-styles/styles.tsx
Wee little PR. Change body font-family, add hover underline to an a tag as directed in first couple of bullets in [document](https://docs.google.com/document/d/1OUzZnV4S9JGqUULkbTOEKUs4HTzqB73gsPuvqS2buC0/edit)
Part of #534
Note: first PR for this issue, probably several more coming.
> minor ui tweaks

- src/page-multi-facility/ScenarioLibraryModal.tsx
> Fix owned/shared scenario library cards overlap issue
Closes #524
> #524 fix overlap issue in Scenario Library Cards

- src/impact-dashboard/CurveChart.tsx
- src/page-multi-facility/projectionCurveHooks.tsx
> Replace "People" with "Inmates" & "Staff" in chart tooltip
**Before:**
**After:**
Closes #372
> #372 chart tooltip: replace People with Inmates & Staff

- src/@types/us-zcta-counties/index.d.ts
- src/database/index.tsx
- src/database/type-transforms.tsx
- src/database/utils.tsx
- src/facilities-context/FacilitiesContext.tsx
- src/facilities-context/actions/referenceFacilities.tsx
- src/impact-dashboard/EpidemicModelContext.tsx
- src/impact-dashboard/LocaleInformation.tsx
- src/locale-data-context/LocaleDataContext.tsx
- src/page-multi-facility/LocaleDetails.tsx
- src/page-multi-facility/types.tsx
- src/page-response-impact/ResponseImpactDashboard.tsx
- src/page-response-impact/ValidDataWrapper.tsx
- src/page-response-impact/hooks/useSystemWideData.tsx
- src/page-response-impact/responseChartData.tsx
- src/page-weekly-snapshot/NYTDataProvider.tsx
- src/page-weekly-snapshot/WeeklySnapshotPage.tsx
> Rename "state" and "stateCode" to "stateName" where relevant
Closes #135
> Rename "state" and "stateCode" to "stateName" where relevant

- backend/python-functions/data_ingest.py
- backend/python-functions/deploy.py
- backend/python-functions/main.py
- backend/python-functions/requirements.txt
Google Cloud Function used to download, reshape, and persist daily Covid case data.  This function expects that a CSV file will be transferred into a specific Google Storage Bucket each day from the mainline Recidiviz Google Cloud project.  Upon arrival, this function will be triggered and will execute.
Closes #566 
> Ingest Covid Case Data on a Daily Basis

- src/database/index.tsx
See the write up in the [accompanying issue](https://github.com/Recidiviz/covid19-dashboard/issues/592) for full context and a description of this bug.
Closes #592 
> Prevent the App from Continuously Creating Multiple User Documents

- src/database/type-transforms.tsx
Handles existing data that doesn't match our updated schema for model inputs so that it is displayed correctly. (the saved data should take on the new schema the next time it is saved.)
Closes #599 
> map stateCode to stateName when reading model inputs from DB

- src/database/index.tsx
- src/database/type-transforms.tsx
- src/impact-dashboard/CurveChart.tsx
- src/page-weekly-snapshot/FacilityProjections.tsx
- src/page-weekly-snapshot/LocaleSummary.tsx
- src/page-weekly-snapshot/NYTDataProvider.tsx
- src/page-weekly-snapshot/WeeklySnapshotPage.tsx
Confirmed this PR is a no-op when against master.
> Production Release: June 18, 2020

- src/database/index.tsx
This is a bug fix release that circumvents an issue preventing the successful sharing and duplication of scenarios.
Confirmed this is a no-op when issued against master.
> Production Release: June 30, 2020

- src/database/index.tsx
- Firestore does not like when you send it undefined values so we'll explicitly remove them from our payloads to avoid this condition.
> Description here
Closes #629 
> Omitting undefined Values from Payload Submissions

- src/database/index.tsx
- src/impact-dashboard/FacilityInformation.tsx
- src/impact-dashboard/ImpactProjectionTable.tsx
- src/impact-dashboard/ImpactProjectionTableContainer.tsx
- src/page-multi-facility/AddCasesModal/AddCasesModalContent.tsx
- src/page-weekly-snapshot/FacilitySummaries.tsx
- src/page-weekly-snapshot/FacilitySummaryRow.tsx
- src/page-weekly-snapshot/WeeklySnapshotPage.tsx
- src/pages/weekly-snapshot.tsx
This is a bug fix release that cures, once and for all, errors we were seeing on writes to Firestore as a result of undefined values under certain circumstances.
Confirmed this is a no-op when issued against master. Manually tested locally.
> Production Release: July 2, 2020

- src/page-weekly-snapshot/FacilityPage.tsx
- src/page-weekly-snapshot/FacilitySummaries.tsx
- src/page-weekly-snapshot/Page.tsx
- src/page-weekly-snapshot/SnapshotPage.tsx
- src/page-weekly-snapshot/SystemWideProjectionChart.tsx
- src/page-weekly-snapshot/WeeklySnapshotPage.tsx
Updates the weekly snapshot page to make it easier to work with and only load data once in the top level component.
-Loads the scenario and facility data in the top level component and passes to children
-Adds a `Page` component with header, subheader, and footer for consistent styling across snapshot pages
I ended up doing this work as I was working on the System Summary 7 day case count chart #597 . Since that will not be done today I will put this work up and continue that next week.
Part of #597 
> [Report automation] Update structure of weekly snapshot page

- src/database/index.tsx
- src/page-weekly-snapshot/FacilityPage.tsx
- src/page-weekly-snapshot/FacilitySummaryTable.tsx
- src/page-weekly-snapshot/SystemWideProjectionChart.tsx
- src/page-weekly-snapshot/SystemWideSummaryTable.tsx
- src/page-weekly-snapshot/shared/utils.tsx
* Moved functions to calculate facility metrics into a shared `utils` file
* Calculated and displayed system-wide metrics in weekly snapshot
Testing:
Closes #596
> Add System Summary Table to Weekly Snapshot

- backend/python-functions/data_ingest.py
Reflects a change in the expected file format from BigQuery export. Behavior verified with example file exports provided by Julia, against the `reference_facilities_dev` collection.
Closes #697 
> ingest reference data in JSON Lines format

- backend/functions/package.json
- backend/functions/yarn.lock
- backend/python-functions/realtime_rt.py
- backend/python-functions/test.py
- src/infection-model/__tests__/curves.test.tsx
- src/infection-model/seir.tsx
This release includes a bug fix in the epidemic model projections to handle valid corner cases where where the total population is less than total cases within a certain subset of the population.
Verified that issuing this PR against master is a no-op.
This release includes a bug fix in the epidemic model projections to handle valid corner cases where where the total population is less than total cases within a certain subset of the population.
Verified that issuing this PR against master is a no-op.
> Production Release: November 4, 2020

- package.json
- yarn.lock
Resolves a security alert. Bundle analysis indicates that this package is not in the client application bundle, only the build tooling, so no deployment is necessary to patch any vulnerability.
Closes #735 
> force nth-check resolution

- README.md
- backend/README.md
This updates the README to make it clear that the app has been decommissioned and no further work is planned.
N/A
> Adds decommission notes in the readme
