src/entry-point/App.tsx, src/page-form/FormPage.tsx, src/page-test/TestPage.tsx, src/styles.ts, src/styles.tsx
This PR:
- adds global styles based on [Juan's css file ](https://recidiviz.slack.com/archives/G010VACT8F2/p1585333687046500) 
- adds a base for the [form page 
](https://www.figma.com/proto/v43UQeEd1Xkb3w2NgxcWql/%F0%9F%9A%80-Recidiviz?node-id=288%3A4&viewport=183%2C343%2C0.09931680560112&scaling=scale-down-width)
- adds style examples to the `/test` page for each css style
The styles are the following:
We can update them as we build out the real pages! 😄
=> Add global styles + base for form page

src/design-system/InputButton.tsx, src/design-system/InputSelect.tsx, src/design-system/InputText.tsx, src/design-system/InputTextArea.tsx, src/design-system/TextLabel.tsx, src/page-form/components/Form.tsx
Mostly doing this to mark the components that I think will be shared between the two forms. Named the components starting with `Input` so that when `src/design-system` is sorted alphabetically, similar components appear next to each other!
File moves and import changes were done automatically by VSCode, so there shouldn't be any typos.
I understand that this could conflict with #24. Let me know if you want me to wait until #24 merges before merging this.
=> Move shared form components into src/design-system

package.json, src/design-system/Colors.tsx, src/entry-point-client/index.tsx, src/impact-dashboard/ChartArea.tsx, src/impact-dashboard/CurveChart.tsx, src/impact-dashboard/CurveChartContainer.tsx, src/impact-dashboard/CurveChartLegend.tsx, src/impact-dashboard/EpidemicModelContext.tsx, src/impact-dashboard/ImpactDashboard.tsx, src/impact-dashboard/ImpactProjectionTable.tsx, src/impact-dashboard/ImpactProjectionTableContainer.tsx, src/infection-model/index.tsx, src/page-test/TestPage.tsx
This adds an additional curve to the chart for Fatalities and also adds a table below the chart that contains some of the same data and some additional metrics, broken out by incarcerated vs staff populations. 
There is a bit of redundancy in the table code; I tried not to build every data structure and table segment completely by hand but I also didn't fuss over making the solution perfectly elegant. There's also a bit of inefficiency here in that we are calculating the same projections twice, which may or may not be desirable in the interest of keeping the components independent of one another. These are things we can revisit later if we decide it's worthwhile but I didn't think they were launch-blockers.
These boxes …
=> Add fatalities curve and output table

src/design-system/Loading.tsx, src/page-verification-needed/VerificationNeeded.tsx
This fixes a type issue that previously caused the `any` requirement. However, I originally sought to solve the issue that when running `yarn dev` the loading spinner is properly centered in the view port, but when running the files in `/dist` after `yarn build` the spinner is in the exact top-left corner. So while this change should definitely be merged, I'd also be interested in knowing if anyone has ideas about why that may be happening.
(As a test I changed the /verify page to just return `<Loading />` directly and it was centered correctly. So something about the way it is invoked in `App.tsx` after `yarn build` is causing the centering to not work.)
=> Fixes type issues in the loading spinner.

src/@types/numeral.d.ts, src/impact-dashboard/EpidemicModelContext.tsx, src/impact-dashboard/ImpactProjectionTableContainer.tsx
This adds a more explicit interface for only the columns we actually need from the model spreadsheet. It also adds an estimate of initial cases (using the same methodology as the Excel model) to seed the model with.
After the initial update, it now selects all the necessary generic inputs to plot the entire US in the chart and table, so that chart should now load properly and display something meaningful after the page loads. @szhu you are probably already aware that we are going to have to do something similar every time a new state or county is selected from the input forms (this is still a loose end in the data flow from my perspective but may already be part of what you're doing? let me know if this is something I can help with in the morning).
(also realized that I forgot to replace …
=> Clean up model data fetching from spreadsheet

src/impact-dashboard/EpidemicModelContext.tsx, src/impact-dashboard/ImpactDashboard.tsx
This activates the State and County pickers and makes sure data flows properly from our spreadsheet datasource to the forms, chart, and table. 
Worth noting that at the moment the "confirmed case count" input doesn't change the model anymore (because we are always using the breakdown figures instead) but it's still useful as a reference so I left it alone for now. (The input component doesn't seem to support disabling at the moment? we can always fix that later)
=> Wire up locale selector

src/impact-dashboard/ImpactProjectionTable.tsx, src/impact-dashboard/ImpactProjectionTableContainer.tsx
We were printing the hospitalized population on the day it crossed the 50% threshold, rather than how many days. We were also failing to include people who were previously hospitalized in the "overall" hospitalized counts. This fixes that! 
(also fixes table display to limit unnecessary width restriction; the page never gets wide enough to make that really necessary)
=> Fix bug in output table

src/design-system/InputSelect.tsx
Fixing a small padding issue so that the Select Inputs match the visual height of the text-based inputs.
=> Updating InputSelect Padding to Fix Sizing Issue with Text-based Inputs

src/infection-model/index.tsx
- Fixes a bug in the code where we are trying to use undefined and NaN values to populate the SEIR model and generate the graphs.  Obviously that won't work.  To fix this bug, we default all age population inputs to zero if they would otherwise be undefined.  This allows us to proceed with the calculations.
Fixes a bug in the code where we are trying to use undefined and NaN values to populate the SEIR model and generate the graphs.  Obviously that won't work.  To fix this bug, we default all age population inputs to zero if they would otherwise be undefined.  This allows us to proceed with the calculations.
**Before**
**After**
=> Defaulting Age Group Population and Infected Numbers to Zero

src/impact-dashboard/EpidemicModelContext.tsx, src/impact-dashboard/ImpactDashboard.tsx
This uses @notfelineit 's new hook to persist form context data to the URL for sharing, bookmarking, etc. It wound up being way more of a beast than I expected but here is where it's at right now:
- updates to the location and facility inputs trigger a history state replacement (meaning no back/forward navigation)
- upon the initial page load, any existing URL parameters are incorporated into the existing state
I initially hoped to preserve back/forward navigation, but I got too deep in the weeds and ultimately abandoned that for now. I think it's still possible but maybe can follow later (unless someone has a quick solution that has evaded my pudding brain today).
There were some challenges that I worked around for now: having the `useQueryState` maintain the same reference across …
=> Persist model inputs in URL

index.html, manifest.webmanifest
Previous PR: #57 
When compiled statically:
- The HTML references `/public/manifest.json`, which exists
- `/public/manifest.json` references `android-chrome-192x192.png`
- `/public/android-chrome-192x192.png` doesn't exist. It exists at `/android-chrome-192x192.png`
This PR fixes those references -- hopefully I got it right this time!
=> Fix web manifest, part 2

src/design-system/Loading.tsx, src/entry-point-static/generatePageContent.tsx
Fixes the brief mispositioning of the loading spinner when loading the static build.
| Before    | After    |
| ----------| -------- |
| ![before] | ![after] |
[before]: https://user-images.githubusercontent.com/1570168/78952915-f6ed2180-7a8b-11ea-9887-60067dc3cde9.gif
[after]: https://user-images.githubusercontent.com/1570168/78952923-fbb1d580-7a8b-11ea-86da-831eebeed385.gif
This was loaded with devtools set to the "Fast 3G" setting so that the loading state could be captured more easily.
Note: With the animations slowed down, it might seem like the Before experience feels better. It doesn't -- at normal speed, you just see a lot of flashes of content which is very jarring!
---
The change in this PR is fairly simple, but a significant amount of experimentation went into producing the …
=> Fix Loading + stop statically rendering HTML

src/auth/AuthWall.tsx, src/auth/PrivateRoute.tsx, src/entry-point-client/App.tsx, src/entry-point-client/PageList.tsx, src/entry-point-static/build.tsx, src/entry-point-static/generatePageContent.tsx
**Note the reviewers: Please review commit-by-commit!** Each commit is small and clearly describes what is going on.
This PR:
- Cleans up the auth and routing React code. See the commit names for the details!
- Fixes the remaining issue mentioned in #69, which is that when static rendering, a flash of content appears.
Details of the fix: When the auth state is loaded and the user has been determined to not be logged in, the home page shows up again briefly. This occurs:
- When static rendering! (Now that this is fixed, this PR also turns static HTML rendering back on, and it is verified to not be buggy anymore with the Loading component.)
- When PrivateRoute has asked to redirect the page, but the redirect hasn't happened yet.
See the "Fix PrivateRoute not actually gating its contents" …
=> Cleanup auth and routing React code + fix static rendering

index.html, src/entry-point-client/PageList.tsx, src/entry-point-client/index.tsx, src/page-unsupported-browser/UnsupportedBrowserPage.tsx
Show the following page if the user is using a browser that runs into an error running the app JS:
Note that the "unsupported browser" page works because it is rendered statically.
Fixes #72
Closes #68 
=> Add "unsupported browser" page and functionality

package.json, src/database/index.tsx, src/database/utils.tsx, src/hooks/useQueryParams.tsx, src/impact-dashboard/EpidemicModelContext.tsx
(Builds on unmerged PR https://github.com/Recidiviz/covid19-dashboard/pull/85.)
Updates frontend to autosave model inputs as the user changes them. Per discussion with Andrew, hydrating the state via query parameters will still work and will supersede state saved to Firestore. We also decided it's acceptable that selecting a different state/county will blow away saved state (since local state resets) since this persistence should be updated in a matter of days.
Manual testing performed:
1.  Start with all site storage cleared and no data for user in Firestore
2. Go to the app, without any query params, and sign in
3. Change the state selection and a few population numbers
4. Revisit the app (again, no query params) and verify state retained
5. Copy the full URL (with the state params), …
=> Add live model persistence to the frontend

src/design-system/Colors.tsx, src/impact-dashboard/ChartArea.tsx
This changes the color of the hospital beds threshold marker to match the color we use for the "hospitalized" curve. 
The light blue color was a bit rough on the eyes in that small type and dotted line so I tweaked it to a slightly darker shade for better contrast. 
Fixes #79 
=> Change color of "hospital beds" in chart

src/impact-dashboard/CurveChart.tsx, src/impact-dashboard/ImpactProjectionTableContainer.tsx, src/infection-model/seir.tsx
This includes the current day as day zero in all model projections and hopefully eliminates the need for confusing off-by-one adjustments in the UI; consumers of the `getCurveProjections` function output can now always safely assume that the index of a day's data is equal to the number of days from the current day. I updated both the chart and the table to remove any such adjustments.
Closes #83 
=> Include current day in projection output

src/design-system/Colors.tsx, src/design-system/Input.tsx, src/design-system/InputDate.tsx, src/design-system/InputSelect.tsx, src/design-system/InputText.tsx, src/impact-dashboard/ImpactDashboard.tsx, src/impact-dashboard/MitigationInformation.tsx
This adds a dropdown for the user to input a rate of spread factor. The model calculations already accept this value, it just never quite made it into the UI, so no calc updates were required. 
In the process I also made some style tweaks to the input elements for consistency, most notably adding a caret to `InputSelect` as a visual indicator that it's a dropown.
Closes #95 
=> Add R0 selector to input forms

src/design-system/Colors.tsx, src/design-system/PromoBoxWithButton.tsx, src/page-multi-facility/MultiFacilityPage.tsx, src/page-multi-facility/ToggleRow.tsx
Adds a `PromoBoxWithButton` component and renders it on the multi-facility page. This component includes a 'Dismiss' button which for now just hides the promo box. We can tie that click handler to something at a later point.
Closes #108
=> PromoBoxWithButton component

src/@types/svg.d.ts, src/design-system/Colors.tsx, src/design-system/InputButton.tsx, src/design-system/Modal.tsx, src/design-system/ModalDialog.tsx, src/design-system/ModalSteps.tsx, src/design-system/ModalTitle.tsx, src/design-system/icons/ic_close.svg, src/page-multi-facility/AddFacilityModal.tsx, src/page-multi-facility/MultiFacilityPage.tsx
> Adds a Modal component with a ModalTrigger and a ModalDialog. Also adds `@types/svg.d.ts` for importing svgs. 
I'm opening this PR as a WIP, I'll continue adding the following components unless someone else comments that they are working on it!
TODO: 
https://www.figma.com/proto/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=735%3A545&viewport=403%2C338%2C0.09717194736003876&scaling=min-zoom
I am assuming that the actual modal content with the form submission is not part of this task, but let me know if it should be!
Thanks!
Related to #93 
Closes #102
=> Add Modal components for MultiFacilityPage

backend/firestore.rules, src/database/index.tsx, src/design-system/Colors.tsx, src/impact-dashboard/ChartArea.tsx, src/impact-dashboard/CurveChart.tsx, src/impact-dashboard/CurveChartContainer.tsx, src/impact-dashboard/EpidemicModelContext.tsx, src/page-multi-facility/FacilityContext.tsx, src/page-multi-facility/FacilityRow.tsx, src/page-multi-facility/MultiFacilityPage.tsx, src/page-multi-facility/types.tsx
* Adding in a mechanism to query Firestore to grab a user's baseline scenario document and its underlying facilities.
* Passing each of the facility's model inputs to our projection charting code.
Closes #114
=> Adds the Ability to Read and Visualize Model Data from Cloud Firestore

src/entry-point-client/App.tsx, src/impact-dashboard/CurveChartContainer.tsx, src/impact-dashboard/EpidemicModelContext.tsx, src/impact-dashboard/ImpactDashboard.tsx, src/impact-dashboard/ImpactDashboardContainer.tsx, src/impact-dashboard/ImpactProjectionTableContainer.tsx, src/impact-dashboard/LocaleInformation.tsx, src/locale-data-context/LocaleDataContext.tsx, src/locale-data-context/index.tsx, src/page-model-inspection/ModelInspectionPage.tsx, src/page-model-inspection/ModelInspectionPageContainer.tsx, src/page-model-inspection/ModelOutputChartContainer.tsx, src/page-multi-facility/FacilityRow.tsx, src/page-multi-facility/MultiFacilityImpactDashboard.tsx, src/page-multi-facility/MultiFacilityPage.tsx, src/page-multi-facility/types.tsx
This untangles the loading of locale data (from the external spreadsheet) from the provisioning of an `EpidemicModelContext` and moves it to a new `LocaleDataContext` that I have just made globally available for now because multiple pages need it. Marshaling the required data to display a single facility now requires three roughly hierarchical contexts to be present: `LocaleDataContext`, `FacilityContext`, and `EpidemicModelContext`.  
`EpidemicModelContext` is much cleaner now because it no longer has to deal with the loading state of the locale data — it requires a source of locale data to be passed in when provisioned. It also does not bother with auto-saving or URL state management anymore, because we are no longer doing those things.
In terms of regression, I made sure that the …
=> Separate locale data from EpidemicModelContext

src/impact-dashboard/EpidemicModelContext.tsx
Following up on my comments on #138 I have fixed the issue with locale data ... as @sprad suspected there was a bug in the reset logic. Fixing it means we can remove `confirmedCases` and `hospitalBeds` from the saved model objects and join that saved data with the proper external locale data.
Now that the form is intended for a specific facility only, I don't really think that seeding the incarcerated population inputs with state- or county-wide data is such a sensible default anymore, so I just took that out. There is now just a single function to get all the default values for a locale and ensure that all required context fields are populated (which includes some metadata fields that are not locale-specific).
none
These …
=> properly initialize model context with locale data and saved model

src/page-multi-facility/FacilityInputForm.tsx
* Previously, the projection chart and table were a bit "smooshed" on the right hand side of the screen.  Adding specific width styles to more cleanly layout the page.
**Before**
**After**
N/A
=> Fixing Spacing Issue on the Facility Page

src/design-system/Colors.tsx, src/design-system/InputButton.tsx, src/design-system/Modal.tsx, src/page-multi-facility/FacilityRow.tsx, src/page-multi-facility/MultiFacilityImpactDashboard.tsx
This picks up where @sprad left off in #146 to complete the delete functionality with a confirmation modal and refresh of the facility list to remove the deleted item.
There weren't mocks for the delete modal so I had to freestyle ... note the fact that our modal component does not have a configurable size at the moment so it looks a little roomy. @cawarren let me know please if there's something you want me to change in this flow. (e.g. closing the modal is equivalent to clicking "cancel" so maybe that's redundant but I erred on the side of caution.)
Closes #147 
=> Enable deleting a facility

src/entry-point-client/PageList.tsx, src/page-multi-facility/FacilityInputForm.tsx, src/page-multi-facility/FacilityRow.tsx, src/page-multi-facility/MultiFacilityImpactDashboard.tsx
This updates routes so that the multi-facility page is now site home, and the facility edit page is now at `/facility`.
none
=> move multi-facility page to site home

src/page-multi-facility/FacilityInputForm.tsx, src/page-multi-facility/LocaleInformationSection.tsx, src/page-multi-facility/types.tsx
Update to persist the selected system type (jail vs. prison) for a facility. UI was already in place.
Per discussion with Andrew, the selected type may be used to pre-populate model inputs, but it's not expected to be used as an input itself.
=> Persist system type at facility level

backend/firestore.rules, src/database/index.tsx
Users should be able to continue to access existing scenarios as expected. I tested this with existing scenarios and in the initial flow when the user doesn't yet have a baseline scenario.
Closes #118
=> Update Firestore security rules and Firestore queries so that users can only access their own scenarios

src/page-multi-facility/FacilityInputForm.tsx
I considered adding validating the name is entered and displaying an error if it's not but thought it a slightly better user experience to just provide a default name that they can rename if they desire. Open to being wrong on this one!
I tested that this saves the facility model successfully with the title of "Unnamed Facility" and that saving multiple models in this way does not break. Multiple models with the same name is acceptable.
Related to #70 
=> Adds default facility name in case users forgets to set one

src/page-multi-facility/ProjectionsHeader.tsx
The projection headers are just text, but the mocks call for bullet point circles before each header, with the appropriate color. Now it looks like:
Related to #70 
=> Adds circles with proper colors for the projection headers

src/page-multi-facility/CreateBaselineScenarioPage.tsx
According to the mocks, after the welcome modal is clicked through we should go straight to the facility details page, not the scenario details page. This updates that, and in the process gets around a bug that caused the modal to not disappear after clicking okay (since the modal route is the same as the scenario details route, `history.push` doesn't seem to redirect).
Related to #70 
=> Changes the welcome modal redirect to facility page

src/page-multi-facility/FacilityInputForm.tsx
As originally revealed [here](https://github.com/Recidiviz/covid19-dashboard/pull/143#discussion_r410909753), there is a race condition on save where if the page that we navigate to loads before the save is complete, then an error is returned as the next page attempts to call a function on a field in the model which is not yet non-null. Specifically, the error happens at `updatedAt.toDate()` on L112 in `FacilityRow`. However, I think just fixing that field would begin a game of whack-a-mole and eventually another field would get invoked and cause a different break.
Since `database/index.saveFacility` returns a Promise, I think this is the way to avoid the race condition by ensuring the navigation to the next page happens only once the save has completed. We're not using a `catch` for any …
=> Adds promise resolve to avoid race condition on save

src/page-multi-facility/MultiFacilityImpactDashboard.tsx
Because the multiple `EpidemicModelContext` objects on the dashboard were keyed by index, they were susceptible to getting out of sync with their underlying facility data after one was deleted. Keying them off the facility's unique ID prevents that.
Fixes #158 
=> link EpidemicModelProviders to specific facilities

src/design-system/InputText.tsx, src/design-system/InputTextNumeric.tsx, src/impact-dashboard/EpidemicModelContext.tsx, src/impact-dashboard/FacilityInformation.tsx, src/infection-model/index.tsx, src/infection-model/seir.tsx
Allows users to enter an expected 3-month population turnover rate, which we will use to adjust the given population numbers to account for population change over time.
Because this is implemented in the Excel model, I verified the JS output against the Excel output for correctness.
Also includes a UI improvement for percentage inputs that more clearly indicates to the user that a value is a percentage (we were previously working around this by adding "(%)" to the input labels because an earlier implementation of this feature was incomplete), and some refactoring of the form layout components. (This was actually done a week or so ago but it seems to have weathered all the subsequent UI changes without any problems so I left it in.)
Closes #61 
These boxes should be checked by the …
=> Include population turnover in calculation model 

src/page-multi-facility/MultiFacilityImpactDashboard.tsx
remove `h-screen` class from `MultiFacilityImpactDashboardContainer` to prevent it from having a `height = 100vh`. I believe you would only want that on `...Page` components (as elsewhere in the app).
Part of [#167 ]
> P1: Multi-facility page scrolls for no reason (nothing down there)
=> remove height scroll on multi facility dashboard

src/entry-point-client/PageList.tsx, src/site-header/SiteHeader.tsx
update page title and remove subhead
change page title from `Page Name • COVID-19 Dashboard` to `Recidiviz • Covid-19 Incarceration Model • Page Name`. For home page (and default), will just say `Recidiviz • Covid-19 Incarceration Model`
I worked with Andrew sending screenshots and we arrived at this design.
Part of [#167 ]
> P1: Remove ‘COVID-19 INCARCERATION MODEL’ in page header / top nav, make the page title ‘Recidiviz | Covid-19 Incarceration Model’
=> update page title and remove subhead

src/design-system/icons/ic_add.svg, src/design-system/icons/ic_folder.svg, src/page-multi-facility/MultiFacilityImpactDashboard.tsx, src/page-multi-facility/ScenarioSidebar.tsx
straighten out fonts, colors, and icons for `Scenario Name` and `+ Add Facility` as per Figma designs.
Part of #167
> ‘Add Facility’ is larger than ‘Baseline Scenario’, doesn’t have circled plus sign
=> multi-facility dashboard: fix up headings and add icons per design

src/page-multi-facility/LocaleInformationSection.tsx, src/page-multi-facility/ScenarioSidebar.tsx
and fix .map warning
1. simple copy change per master copy spreadsheet
2. rider fix for _element must have unique key..._ warning due to `undefined` value.
Part of #167 
> P1: Daily reports promo copy has typo → update to final copy, resolve ‘DailyReports’ concatenation
=> daily reports copy swap

src/design-system/InputText.tsx
A change to the `InputText` component in #171 caused the component to collapse outside of the table context where it was mostly being used, which I didn't realize because I failed to test it thoroughly enough. Sorry! This fixes that. I verified that there is no regression anywhere else I saw this component being used.
none
=> make sure InputText container doesn't collapse

src/database/index.tsx
* Updating the data model and persistence layer to allow for the versioning of model inputs.
Closes #166
The following tests were performed locally:
1.  Create a brand new scenario-less user; Add a facility; Verify model inputs and a versioned copy were saved as expected. ✅
2.  Update a facility's fields; Verify model inputs and a versioned copy were saved as expected. ✅
3.  Remove fields (i.e set `age85Cases` and `age85Population` to empty in the form);  Verify model inputs and a versioned copy were saved as expected. ✅
4.  Adding multiple planned releases.  Verify model inputs and a versioned copy were saved as expected. ✅
5.  Add a new facility to an existing Scenario.  Verify model inputs and a versioned copy were saved …
=> Version History Support for Facility Inputs

src/impact-dashboard/CurveChart.tsx, src/impact-dashboard/CurveChartContainer.tsx, src/page-multi-facility/FacilityRow.tsx
1. remove Y axis tick values
2. add more Y axis ticks/gridlines
3. remove X axis label
4. remove margins (where labels would go)
5. reduce chart height from 200 to 144 per design
Part of #167 
> P1: Charts should not have axes or labels
=> remove chart labels from Facility list

src/design-system/ChartTooltip.tsx, src/design-system/ChartWrapper.tsx, src/design-system/Colors.tsx, src/impact-dashboard/CurveChart.tsx, src/rt-timeseries/RtTimeseries.tsx, src/rt-timeseries/RtTimeseriesContainer.tsx, src/rt-timeseries/index.tsx
Creates a new chart for a new metric we are developing, R(t) (rate of spread over time). As this is a statistical model we also show the confidence intervals. Features in common with the `CurveChart` (tooltip, axis styles) were factored out to the design system for reuse. 
(There are some slight differences from the mocks due to some design issues that are still being worked out but they don't have any major implications for this PR, so no reason to hold it up IMO.)
I also included a container component that does some data transformation on some fake data, which I was using for development. I don't think the transformation logic is likely to change much once it's wired up, but if we think it's a bad idea to commit the dummy data to `master` I can take that out. (I'm of two minds; I think …
=> Timeseries chart for R(t)

src/impact-dashboard/CurveChart.tsx
> Set the x-axis for the curve chart output on the add facility page to 25 increments (0-100)
NOTE: I wasn't sure if this needed to be a function fo the x-axis data so I directly set the tick values to 25 increments from 0-100 since the data currently goes to 85. This was the easiest way to set this that I could tell from the docs, but I could spend more time with it if we need it to be responsive to changes in the length of `days`. 
Part of #167 
=> Add tick values in increments of 25 to facility output chart

src/design-system/HelpButtonWithTooltip.tsx, src/design-system/InputLabelAndHelp.tsx, src/design-system/TextLabel.tsx
Changes the background color for tooltip icons to lighter green. Issue mentions `FacilityInputForm` specifically bug after checking with @cawarren I got the go ahead to change it globally.
Also fixes a styling bug in `TextLabel`
Closes #213 
=> change tooltip help icon to softer green

src/database/__tests__/testcases.tsx, src/database/index.tsx, src/entry-point-client/App.tsx, src/page-multi-facility/CreateBaselineScenarioPage.tsx, src/page-multi-facility/FacilityInputForm.tsx, src/page-multi-facility/FacilityPage.tsx, src/page-multi-facility/FacilityRow.tsx, src/page-multi-facility/MultiFacilityImpactDashboard.tsx, src/page-multi-facility/MultiFacilityPage.tsx, src/page-multi-facility/ScenarioSidebar.tsx, src/page-multi-facility/types.tsx, src/scenario-context/ScenarioContext.tsx, src/scenario-context/index.tsx, src/scenario-context/useScenario.tsx
This work was done to unwind the assumption that there is only ever a single scenario (i.e. the Baseline) that we can hang all of our other data off of.  Instead, the work here will allow additional features to be created in the context of a multiple scenarios world.
Note:  This PR does not add any new functionality.  It simply lays the foundation for the mutli-scenario work as outlined by #168 which will additionally require more persistence changes for things like listing all scenarios, duplicating a scenario, deleting a scenario, etc.
Closes #129 
=> 129 unwind persistence from baseline scenario

src/impact-dashboard/LocaleInformation.tsx, src/locale-data-context/LocaleDataContext.tsx, src/page-multi-facility/LocaleDetails.tsx
> Adds the auto-populating locale information section on the facility page. 
@macfarlandian I'm not sure if I'm using `LocaleDataProvider` as intended, let me know if it would be better to pass in the `model` from the `LocaleInformation` component. I noticed they have different property names and data structures. Also, neither of the data models had a field that looked similar to `ICU Beds`, so I currently left that in as blank. thanks for your help!
Closes #214 
Part of #167 
=> Add auto-populating non-editable locale information to facility page

src/design-system/TextLabel.tsx, src/impact-dashboard/FacilityInformation.tsx
* Remove "This section collects…" description under "Facility Details" section
* Update input label color to match styling in mocks. 
* 👉 Note / question: The [doc](https://docs.google.com/document/d/1UDnCCVe9yZ_V65McixIOdqnQPhACFHCvKNxSG0pKulI/edit) mentioned caps, not sure what you mean? Didn't match the [Figma](https://www.figma.com/file/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=964%3A0) exactly, e.g. did not bump font size from 12px to 10px.
* This will globally affect `TextLabel`, is that ok?
WAS:
IS:
Addresses some of: https://github.com/Recidiviz/covid19-dashboard/issues/167
=> Update "Facility Details" section

src/design-system/Input.tsx, src/design-system/InputText.tsx, src/design-system/InputTextArea.tsx, src/design-system/TextLabel.tsx
* Update default color for WrappedInput
* Change "Facility Details" > data fields color, and globally
* Update data fields font styling 
* Change styling of "Facility Details" input labels
* With the font styling change of the inputs, the input labels such as "FACILITY STAFF", "CURRENT CASES" didn't match what's in Figma.
Ref: https://www.figma.com/file/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=964%3A0
WAS:
IS:
Addresses some of: #167 (finishes it?)
=> Design tweaks under "Facility Details"

src/database/__tests__/testcases.tsx, src/database/index.tsx
Updating the persistence layer to support accessing all of the Scenarios created by a user such that they can create a "model library" to test multiple scenarios at their facilities.
Closes #255 
=> Update Model Persistence to Support Accessing Multiple Named Scenarios

.gitignore, backend/.gitignore, backend/python-functions/main.py, backend/python-functions/realtime_rt.py, backend/python-functions/requirements.txt, backend/python-functions/schemas.py, backend/python-functions/test.py, src/infection-model/rt.tsx
Replaces the placeholder `calculate_rt` function with real computation. Credit where due: everything in `realtime_rt` is the handiwork of @justkunz; all I really did was construct the response object and write tests. 
I also changed the API to pass the dates as strings instead of timestamps. This conforms better to what the compute function expects, but it also has the benefit of being more explicit and able to be validated as a proper date by the schema, so it's better all around IMO.
I tested this end-to-end on top of #250 and verified it works! (The fetches generally took ~2-3 seconds with just two days of data, FWIW.)
Part of #62 
=> Do real Rt calculation in the python cloud function

package.json, src/impact-dashboard/CurveChartContainer.tsx, src/impact-dashboard/FacilityInformation.tsx, src/impact-dashboard/ImpactProjectionTableContainer.tsx, src/infection-model/__tests__/curves.test.tsx, src/infection-model/index.tsx, src/infection-model/seir.tsx, src/page-model-inspection/ModelInspectionTableContainer.tsx, src/page-model-inspection/ModelOutputChartContainer.tsx, yarn.lock
Both the R(t) feature and Excalibur are going to need to generate curves based on arbitrary rate of spread factors that aren't captured by our existing low/med/high enums. This PR changes the interface for our curve functions to just require numeric inputs. 
There was existing logic in the curve function to translate the enum key into numeric values; that has been factored out into a separate function. Components that were dumping the `EpidemicModelContext` directly into curve functions now need to use this new function to transform the context data structure first. Future components for the features mentioned above may provide these values by other means, which may or may not depend on the enum value selected by the user. There may come a point where we deprecate and remove that enum …
=> Curve functions accept numeric rate of spread

src/design-system/InputDescription.tsx, src/design-system/PopUpMenu.tsx, src/page-multi-facility/FacilityInputForm.tsx, src/page-multi-facility/FacilityRow.tsx, src/page-multi-facility/ScenarioSidebar.tsx
* Use InputDescription instead of InputTextArea in FacilityRow
* Make persistChanges more specific
* Remove padding from component level 
* Correspondingly, re-implement spacing in page, with margin (cause between elements)
WAS:
IS: only visual change to facility row, not elsewhere
Closes https://github.com/Recidiviz/covid19-dashboard/issues/196
---
Let me know if should make any changes!
Thanks @szhu for your help! 💯
---
From talking to szhu and @cawarren, next tasks could be these things, lmk if any preferences:
**Follow-ons I can do:**
- Fix InputNameWithIcon to not have the text size jump
- Rename InputDescription to something like InputTextAreaEditable since …
=> Make FacilityRow text input behavior match Scenario Details section

src/design-system/Spacer.tsx, src/page-multi-facility/FacilityInputForm.tsx, src/page-multi-facility/FacilityRow.tsx, src/page-multi-facility/ScenarioSidebar.tsx
* Fix Spacer component by adding rem suffix
* Used rem based off of https://tailwindcss.com/docs/margin/
* Refactor to use Spacer instead of a blank div 
* Based off changes made in #274
IS (no visual change):
N/A, refactor
N/A, should I make one? 
Follow-on to https://github.com/Recidiviz/covid19-dashboard/pull/274
=> Tweak Spacer component, then use it

backend/firestore.rules, src/constants/index.tsx, src/database/index.tsx, src/design-system/DateFormats.tsx
Adding the persistence layer code to allow for duplicating scenarios
Closes #175 
Upon duplication a scenario I confirmed that:
1.  A new scenario was created with the requested name and description copy ✅ 
2.  All existing facilities and their modelInput versions were copied over ✅ 
Additional Cases:
1.  Tested that copying a Scenario without any facilities worked ✅ 
2.  Throwing an exception within the batch performs a rollback on the commit ✅ 
Performance:
I "performance tested" this by duplicating a Scenario that had 10 facilities and each of those facilities had 8 versions of modelInputs.  The duplication ran in about 2-3 seconds.  I think this should be fine for most cases, but we'll need to keep an eye on this if we …
=> Adding Support for Duplicating Scenarios

backend/python-functions/realtime_rt.py, src/impact-dashboard/ChartArea.tsx, src/impact-dashboard/CurveChart.tsx, src/impact-dashboard/CurveChartContainer.tsx, src/impact-dashboard/ImpactProjectionTableContainer.tsx, src/infection-model/index.tsx, src/infection-model/rt.tsx, src/infection-model/seir.tsx, src/page-model-inspection/ModelOutputChartContainer.tsx, src/page-multi-facility/FacilityContext.tsx, src/page-multi-facility/FacilityInputForm.tsx, src/page-multi-facility/FacilityProjections.tsx, src/page-multi-facility/FacilityRow.tsx, src/page-multi-facility/__tests__/projectionCurveHooks.test.tsx, src/page-multi-facility/projectionCurveHooks.tsx, src/page-response-impact/responseChartData.tsx, src/rt-timeseries/RtTimeseries.tsx, src/rt-timeseries/RtTimeseriesContainer.tsx
When enabled by feature flag, this uses the latest fetched R(t) value as the "rate of spread" input to the projection model. (When not enabled, there should be no change in functionality.)
A few things had to happen to enable this:
- I ran into trouble with the new curve function hooks I just wrote, because I forgot you can't use hooks conditionally (they have to run in the same order on every render), so now there is just one hook for getting the curve that takes optional Rt input, and decides what data transformations to apply based on that.
- Based on advice from @justkunz I also lifted more logic related to the qualitiative R0 user input out of the curve function and into the related data transformation, to make sure it was not erroneously applied to Rt input.
- All the projection …
=> Use R(t) value in projection model

src/impact-dashboard/ImpactProjectionTableContainer.tsx, src/page-response-impact/PopulationImpactMetrics.tsx, src/page-response-impact/ResponseImpactDashboard.tsx, src/page-response-impact/responseChartData.tsx, src/page-response-impact/utils/ResponseImpactCardStateUtils.tsx
1. Calculate hospitalizations and fatalities across all facilities for current scenario for both staff and incarcerated.
2. repeat for original scenario
3. pass data into cards
Most of the heavy lifting is in the `ResponseImpactCardStateUtils` file. `ResponseImpactDashboard` assembles and maintains the state for the data object. A couple other files I just needed to export some functions, and then the card container I needed to pass those props down and hook the data up.
Closes #281 
=> [Excalibur] response impact - reduction card data

src/page-response-impact/ProjectionCharts.tsx, src/page-response-impact/ResponseImpactDashboard.tsx, src/page-response-impact/responseChartData.tsx, src/page-response-impact/styles.tsx
While we wait for more information about the populations for current and original, this PR does some light refactoring for the dashboard component:
- Move charts to a ProjectionCharts component
- Move styled components to a styles.tsx file
- Move helper get functions to the responseChartData file
I'm not sure what type of change to select for a refactor/cleanup
=> [Excalibur] Refactor ProjectionCharts into its own component

src/page-multi-facility/MultiFacilityPage.tsx
Add vertical padding for the loading indicator when loading on MultiFacilityPage.
Currently this loading indicator is attached to the header border and looks broken.
> Description here
None
=> [nit] Add vertical padding for the loading indicator when loading

src/infection-model/seir.tsx
We were extrapolating the number of initially exposed people from the number of initial cases, but failed to clamp the maximum value at the total population size, which could lead to negative values in the "susceptible" curve. This fixes that! Really it just ports over the fix from Python, where @justkunz had already implemented it.
Closes #272 
=> don't let initial exposed estimate exceed total population

.eslintrc.json, src/design-system/InputDescription.tsx, src/design-system/InputNameWithIcon.tsx, src/design-system/InputText.tsx, src/design-system/InputTextArea.tsx, src/page-multi-facility/FacilityInputForm.tsx, src/page-multi-facility/FacilityRow.tsx, src/page-multi-facility/ScenarioSidebar.tsx
Add validation for Scenario name & description and Facility name
- Scenario name & description: keep showing the input field if empty
- Facility name:
- Set focus on the input field on page load
- Keep showing the input field on blur/mouse out
- If facility name is empty, Scroll top on "Save" clicked
Before:
After:
Closes #197
=> Add validation for Scenario name & description and Facility name

src/database/type-transforms.tsx, src/page-multi-facility/ScenarioSidebar.tsx, src/page-multi-facility/types.tsx
Adds a new scenario promo to highlight new Rt charts and puts it at the top of the priority queue. Requires a runtime migration/monkeypatch for users who have not yet saved the new flag to their database.
Closes #303 
=> Add promo message for Rt

src/impact-dashboard/FacilityInformation.tsx, src/page-multi-facility/FacilityRow.tsx
Case counts by age groups is initially collapsed in the modal. On click, it expands to include the age specific rows.
Closes #305
=> Add collapsible age rows for case count update modal.

src/design-system/Modal.tsx, src/design-system/ModalDialog.tsx, src/design-system/icons/ic_duplicate.svg, src/page-multi-facility/AddCasesModal.tsx, src/page-multi-facility/FacilityInputForm.tsx, src/page-multi-facility/FacilityRow.tsx
Refactors the add cases modal into a separate component for reuse, and then reuses it on the facility page. (Some of the modal state management boilerplate I was able to delegate to a `Modal` component that we already had but weren't using for anything.)
Closes #304 
=> "Add cases" button on the Facility page

src/page-multi-facility/FacilityRow.tsx, src/page-multi-facility/MultiFacilityImpactDashboard.tsx
This removes the textarea from `FacilityRow` and makes it so that hovering anywhere in the row's click target (except for the button that opens the Add Cases modal) makes the edit icon appear. Also makes said icon a bit larger, as suggested in the issue. Overall other than the slightly larger icon, nothing should look different, only the post-click behavior (navigating rather than entering an input field) is changed.
Closes #312 
=> Disable name editing in facilities list

.env-example, src/design-system/InputButton.tsx, src/design-system/PromoBoxWithButton.tsx, src/feature-flags/featureFlags.tsx, src/page-multi-facility/ScenarioSidebar.tsx
This PR adds a button to the scenario sidebar "Generate Impact Report" that will navigate to the `/impact` page. I tried to add a feature flag for showing this button so that it doesn't block any releases, let me know if I set that up okay or if I misunderstood how they work!
Closes #229
=> [Excalibur] Add button to scenario sidebar that navigates to /impact

src/page-multi-facility/ScenarioSidebar.tsx
An if statement meant for the name/description fields were unintentionally preventing scenario changes from propagating to the database. This fixes the problem by creating the same check for the name/description in a separate function.
Closes #309 
Closes #317
=> Fix issue preventing scenario changes from updating database

src/design-system/InputDescription.tsx, src/design-system/InputNameWithIcon.tsx, src/design-system/InputTextArea.tsx, src/design-system/PopUpMenu.tsx, src/page-multi-facility/FacilityRow.tsx, src/page-multi-facility/ScenarioSidebar.tsx
- Expands the click target for the facility name and removes the folder icon
- Decreases size of the ellipsis menu
- Eliminates jarring style changes when editing the description, namely the change in typeface and sudden addition of padding. On this one basically I decided to pull the plug on our repeated and unsuccessful attempts to make `InputTextArea` adaptable enough to match the surrounding styles; there didn't seem to be any real benefit to that approach, because there was no boilerplate form handling that was encapsulated by it, and it was resulting in an API that was pretty difficult to use but still didn't actually work as desired. I tried to clean up as much of that as I could. There aren't any regression concerns because this component isn't being used anywhere else so I tried …
=> Assorted UI polish on facility page

src/page-multi-facility/FacilityRow.tsx
Fixes these issues:
- The cases number should be the click target, not the div it’s in
Currently the entire area around the cases number is clickable to get the Add Cases modal. However, this makes it difficult for the user to know whether they’re clicking cases or the facility name (which also has a large click target). The cases number itself should be the click target for the ‘Add cases’ modal.
- Style improvements for cases number click target
The text should gain an underline on-hover
The text should have a tooltip on-hover, which reads ‘Click to add new or previous day cases’
#306 
=> Case counts UI polish

src/design-system/EditInPlace.tsx, src/design-system/InputDescription.tsx, src/design-system/InputNameWithIcon.tsx
Building on the input changes in #326, this applies a similar treatment to the input component that handled scenario and facility names. That involved factoring out most of the UI logic into a separate `EditInPlace` component that takes a component and produces a textarea that mirrors its styles. (I may have been _slightly_ overzealous in trashing the old form behavior in that previous PR; some of it has been resurrected here, most notably the adjustable height feature.)
There should be no regression in the description edit fields for scenarios and facilities, and the name inputs on those respective pages should now behave according to @cawarren 's specifications in our UI polish doc.
Closes #164 
These boxes should be …
=> Prevent jarring style change when editing scenario & facility names

src/impact-dashboard/CurveChart.tsx, src/impact-dashboard/CurveChartContainer.tsx, src/page-multi-facility/FacilityRow.tsx
Removed the hospital beds annotation from scenario page. Annotation is still present on the facility page.
Scenario page:
Facility detail page:
#306 
=> Remove Hospital beds annotation from chart on scenario page.

src/page-multi-facility/ScenarioSidebar.tsx
Remove trailing parenthesis at the end of the sentence
WAS:
IS:
Closes https://github.com/Recidiviz/covid19-dashboard/issues/336
=> Fix typo in Rt promo

src/impact-dashboard/EpidemicModelContext.tsx, src/locale-data-context/LocaleDataContext.tsx, src/page-response-impact/ResponseImpactDashboard.tsx, src/page-response-impact/responseChartData.tsx
As input to the original projection on the `ResponseImpactDashboard`, use the county's `totalJailPopulation` instead of `totalPrisonPopulation` when `systemType='County Jail'`.
Closes #289 
=> [Excalibur] Use County Jail total population when system type is 'County Jail'

src/page-multi-facility/FacilityInputForm.tsx
As discussed in [this Slack thread](https://recidiviz.slack.com/archives/G010VACT8F2/p1588900629168100), there is a bug causing the `modelInputs.observedAt` date (and consequently the latest `modelVersions.observedAt` date) to be set to whatever is the most recent `observedAt` date in the existing list of model versions. I don't know if this is the most elegant fix, but it works in local testing. The approach is to eliminate any uncertainty or ambiguity and just set `observedAt` to right now when entering updates in this form, which is the desired behavior.
Local testing:
- Updated the facility through the facility input form before and after the change. The buggy behavior happens before the change and not after. After, the modelInputs and modelVersions observedAt fields are set to right …
=> Explicitly sets modelInputs.observedAt on the facility details page

src/design-system/Colors.tsx, src/infection-model/rt.tsx, src/page-multi-facility/FacilityRowRtValuePill.tsx, src/page-multi-facility/MultiFacilityImpactDashboard.tsx, src/rt-comparison-chart/RtComparisonChart.tsx, src/rt-comparison-chart/RtComparisonChartContainer.tsx, src/rt-comparison-chart/index.tsx
Adds a new type of chart (currently with fake data and behind a flag) for comparing Rt across all facilities in a scenario. The actual data handling will follow in a subsequent PR.
The only significant issue I ran into was replicating the feature whereby the facility name changes color on hover. The charting library doesn't support it natively (not surprising as it's a pretty rare thing to see in a chart IMO) and while the API is pretty flexible I was finding it inordinately difficult to get it to work. Personally I don't think the chart suffers much without it so hopefully it's OK to just leave it out @cawarren ? We could come back to it later but it didn't seem worth holding up this PR over any further at this point.
Part of #202 
These boxes should be checked by the submitter prior to …
=> R(t) comparison chart

package.json, setupTests.tsx, src/constants/index.tsx, src/infection-model/__tests__/rt.test.tsx, src/infection-model/rt.tsx, src/page-multi-facility/MultiFacilityImpactDashboard.tsx, src/page-multi-facility/PanelHeader.tsx, src/page-multi-facility/ProjectionsHeader.tsx, src/page-multi-facility/ProjectionsLegend.tsx, src/page-multi-facility/RateOfSpreadPanel.tsx, src/rt-comparison-chart/RtComparisonChart.tsx, src/rt-comparison-chart/RtComparisonChartContainer.tsx, yarn.lock
Pipes our fetched Rt data into the comparison chart. Includes functionality to look backward in time at different snapshots of Rt (which I have interpreted as "the most recent Rt value as of X days ago", because that seemed to be the only reasonable implementation of what's in the mocks).
Since the initial load can take a while, rather than waiting to render the entire chart we are rendering it a row at a time as the data comes in, but overlaying the entire chart with a loading spinner until all the fetches are complete.
Closes #202 
=> Add real data to the Rt comparison chart

src/page-response-impact/ValidDataWrapper.tsx
Add an explicit “Back to model” navigation on the error text
Note: I think this should go to the home page since you are coming from the modal to get to /impact.
IS:
Part of: https://github.com/Recidiviz/covid19-dashboard/issues/360 
Closes `P2: Add an explicit “Back to model” navigation on the error text` from https://docs.google.com/document/d/1_jbpbsObUWkakyitmuIMaNKhq1YVU_fpo4j06ip8ets/edit#
=> [Excalibur] Add back button to /impact error page

src/impact-dashboard/CurveChart.tsx
Does what it says on the tin; if they fit, they fit, but we no longer stretch the y axis to accommodate them. Mostly as easy as flipping a switch, but a little extra work was needed to stop them from being rendered and visible outside the bounds of the chart (a plain CSS fix was too blunt and affected other annotations such as tooltips).
Closes #338 
=> exclude hospital beds from y axis range

src/infection-model/seir.tsx
Similar to what we do with fatality rates, this lets us vary the hospitalization rate in our simulations by age bracket. 
Closes #172 
=> vary hospitalization rate by age bracket

src/page-multi-facility/ScenarioSidebar.tsx
Remove the data sharing and daily reports toggles (and their associated promo messages) from the scenario sidebar on the multi-facility view. I left the components themselves in place, since the issue indicates they may still be useful in the future. 
I also didn't change anything in the associated database functions — the default state is not incompatible with the new UI, I figure we may still care about these underlying settings even though they aren't currently exposed on the page, and I didn't want to introduce an inconsistency in the document fields since we don't have a good way to do migrations yet.
Closes #373 
=> Remove setting toggles from Scenario UI

src/page-multi-facility/ScenarioSidebar.tsx
Fixes an issue where the scenario name and description were not being updated in the scenario sidebar after changing scenarios.
The scenario sidebar and its descendants have accumulated some convoluted state management logic that contributed to this bug, and this PR does not do anything to improve that; instead I had to just force its entire component tree to re-render when the scenario changes, which forces all the form inputs to re-initialize.
Closes #348 
=> force sidebar re-render after scenario switch

src/design-system/PageColumn.tsx
Went the "quick fix" route for now so don't have to change the rest of the markup. 
(The column markup is also used on the Add Facility page, which isn't really responsive at all for now, but this fix makes it a little better)
IS:
Part of: #360
=> [Excalibur] Make /impact layout more responsive

src/design-system/InputDate.tsx, src/page-response-impact/BaselinePopulationModal/BaselinePopulationForm.tsx, src/page-response-impact/BaselinePopulationModal/index.tsx
- Change styling of InputDate to match Input on view (Date was larger than other fonts)
- Change modal button fonts (Generate and Back are serif fonts, should be sans-serif / consistent with descriptive text at the top)
WAS:
IS:
---
This also changes the form on the "Add Facility" page, but makes the inputs more consistent:
IS (inputs are matching):
Part of [Excalibur UI polish Google doc]( https://docs.google.com/document/d/1_jbpbsObUWkakyitmuIMaNKhq1YVU_fpo4j06ip8ets/edit)
=> [Excalibur] Modal design tweaks

src/design-system/ModalDialog.tsx
Fix bug in add cases modal in the scenario page where it shows at the top of the page even when the facility row is reachable only by scroll at the bottom.
Verified the modals on facility detail page (add cases and delete) are unaffected.
Before:
After:
Closes [#XXXX]
=> Fix bug in showing add cases modal on scroll.

src/database/index.tsx, src/infection-model/rt.tsx
- Add a new composite index for modelVersions sub collection.
- Changed getFacilityModelVersions to order by observedAt and updatedAt to account for multiple observations on the same day. observedAt is sorted asc and updatedAt is sorted desc.
- Removed the extraneous orderBy done in getRtInputsForFacility, since this is taken care of in the query itself.
- Verified that getRtInputsForFacility returns the same o/p before and after the change.
- No index errors on console due to using the composite index.
E.g. o/p of getRtInputsForFacility selecting only the most recent updatedAt for every observedAt.
Closes #254
=> Change firebase query to use composite index for modelVersions. 

src/page-response-impact/ReducingR0ImpactMetrics.tsx, src/page-response-impact/ResponseImpactDashboard.tsx
Update the copy for the hospital beds used at peak card at the bottom of the page so that it is clearer that it is calculated by incarcerated projection numbers (as opposed to the curve charts which sum both incarcerated and staff numbers)
Closes #400 
=> [Excalibur] Update copy for the hospital beds at peak metric to specify incarcerated

src/page-multi-facility/ScenarioSidebar.tsx
IS:
~~(Note: Not sure if visual oddity with long name on change scenario, can take a closer look separately)~~ nm this is known issue, later on the google doc list!
cc @cawarren 
Part of https://github.com/Recidiviz/covid19-dashboard/issues/372
=> [Merlin] Add baseline indicator on scenario sidebar

src/page-multi-facility/ScenarioLibraryModal.tsx
* Adds the ability to delete scenarios from the Scenario Library and handles the special case of deleting a scenario that is currently being viewed by resetting the currently viewed scenario back to the baseline.
Closes #351 
=> Adding the Ability to Delete a Scenario from the Scenario Library

src/design-system/ModalDialog.tsx
The z-index on absolutely positioned items weren't explicitly set, so the Add New Cases modal was appearing behind the RtPills. The Modal's z-index is now explicitly set to prevent further issues.
Closes #355 
=> Fix z-index issue with rt pills displaying above the modal

src/design-system/Loading.tsx, src/impact-dashboard/CurveChartContainer.tsx
To achieve this, make row full-height on load and account for padding
WAS:
IS:
👉 Please let me know if this is not the right approach. I tried adding a conditional prop to `LoadingContainer` [here](https://github.com/Recidiviz/covid19-dashboard/blob/master/src/design-system/Loading.tsx#L7-L13) but got stuck / couldn't achieve the same result. If not the right approach, any similar components here I could look at? 
FWIW it's good on mobile as-is, seems like the height of the chart is constant.
Part of https://github.com/Recidiviz/covid19-dashboard/issues/372 cc @cawarren @sychang 
=> [Merlin] Make loading spinner appear in center of row

backend/python-functions/realtime_rt.py, backend/python-functions/test.py
Makes two changes to the Rt function requested by @justkunz: 
- drop the first day's Rt value because it is not meaningful and will always be 0 
- drop duplicate case counts in consecutive input records
The difference this produces can be quite dramatic – I tested it with some real-ish data from our aggregated dataset.
Current prod:
After dropping the first day (same values but much more readable):
After filtering out duplicates:
No frontend changes were necessary, the Rt timeseries component already handles this and ensures there are at least two data points returned from the server before attempting to display the chart. (The other Rt features aren't affected by this because they only care about one value at a time.)
Closes #292 
These boxes should be checked by the submitter prior to …
=> Filter first and duplicate records out of Rt function

src/hooks/useFacilitiesRtData.tsx, src/page-response-impact/ResponseImpactDashboard.tsx
I'm sorry for introducing this bug! This PR adds a helper function that selects the `rtData` using the facility IDs on the current scenario for the response impact page. I saw this as the quick way to fix this issue, and if anyone has a suggestion for changing how the state is managed I'm happy to work on that too. I thought about saving the `rtData` by scenario ID and facility ID, but thought that would ripple a lot fo changes throughout and wanted to get a fix up soon. 
Closes #444 
=> Get facilities RtData by facility ID on response impact page

backend/firestore.rules
Distinguishes between owners (full read/write access) and viewers (read only) in Firestore security rules pertaining to scenarios and their descendants. 
I tested these against the `scenario_test` collection in the Firestore rules playground (they are currently deployed for that collection for anyone who'd like to do their own testing) and also verified there are no regressions in the app against that collection with these rules in place. 
Closes #428 
=> Update Firestore rules to support "viewer" role

src/design-system/Colors.tsx, src/page-multi-facility/FacilityInputForm.tsx, src/rt-timeseries/RtTimeseries.tsx, src/rt-timeseries/RtTimeseriesContainer.tsx
When there isn't enough data to generate a Rt chart, show a red box / button "empty state" instead that is the same action as the "Add or update cases" modal.
Question mark icon with tooltip appears conditionally when there is data.
IS:
Part of https://github.com/Recidiviz/covid19-dashboard/issues/280
=> Add Rt empty state aka "not enough data"

backend/firestore.rules, src/auth/README.md, src/auth/react-auth0-spa.tsx, src/database/index.tsx, src/database/type-transforms.tsx, src/page-multi-facility/types.tsx
Creates fetch and save functions for documents in the new Firestore `users` collection. Upon successful authentication, uses these new functions as needed to create or update the corresponding document to store the name and email provided by Auth0. (This is a slightly different approach than what was outlined in the linked tickets, because there is not, as far as I could tell, any way to detect and respond to a new user registration from the Auth0 web client. On the other hand, this also gets us a bonus feature of keeping our records in sync with Auth0 as people revisit the site.)
I also had to update the Firestore security rules, because it turns out there was a flaw in my testing previously and it wasn't actually possible to create a new user document for oneself. These rules (tested in …
=> Add authenticated users to Firestore 

src/page-multi-facility/HistoricalCasesChart/ChartHeader.tsx, src/page-multi-facility/HistoricalCasesChart/icons/ic_plus.svg, src/page-multi-facility/HistoricalCasesChart/index.tsx
Adds the following features from #404 TODO's:
- Change the bar's color to a darker color on hover to signify it as a click target
- Add the chart header with the Cases title and a button that opens the Add Cases modal with yesterday's date pre-selected (or what the current default date is)
Based off Daniela's branch.
Note:
- There is some delay while changing the bar color on hover. It seems to be from the library (using customHoverBehavior). So I changed the hover color to be teal instead of green to make it more obvious. @sychang lmk if this doesn't work.
Other options for this:
1. pieceHoverAnnotation, which changes bar color on hover instantaneously, but doesn't give the tooltip for days with missing data.
2. hoverAnnotation, which will change the color of all bars with data on hover. …
=> Add chart header, bar color change on hover for historical cases graph on facility page.

src/database/type-transforms.tsx
Adds a check before mapping over baselinePopulations in the buildScenario type-transforms function.
Closes [#XXXX]
=> Add a guard for baselinePopulations in buildScenario

src/hooks/useFacilitiesRtData.tsx, src/infection-model/rt.tsx, src/page-multi-facility/MultiFacilityImpactDashboard.tsx, src/page-response-impact/ResponseImpactDashboard.tsx, src/rt-comparison-chart/RtComparisonChartContainer.tsx
I think the bug for this issue came from line 67 in the `RtComparisonChartContainer` component, where it copies the previous chartData state with the new chartData state. I'm not sure the original intention for that, so I hope that this fix isn't breaking another feature I am unaware of. Let me know if there's documentation somewhere or an issue I could look at to see what all the features/use cases of this panel should be. 
My update removes copying in the chartData state and it also removes resetting the chartData state to an empty array when `rtDaysOffset` changes. Instead I added `rtDaysOffset` to the useEffect that is calling `generateChartData`, which should reset the chartData state anytime facilities, rtDataMapping and rtDaysOffset changes. 
Closes #456 
These boxes should be …
=> Bug fix - Displaying the current scenario's facilities' rtData on the rate of spread tab

package.json, src/design-system/Input.tsx, src/design-system/InputDate.tsx, src/design-system/InputSelect.tsx, src/design-system/InputText.tsx, src/design-system/InputTextNumeric.tsx, yarn.lock
Using the "react-debounce-input" package, we now debounce inputs with a debounce time of 1s.
Specifically, using this package, inputs don't pass up their new values unless:
- 1s has passed without any user interaction, or
- the focus has left the input (the user has clicked or tabbed away), or
- the user presses the Enter key.
(For future reference, the last two triggers can be easily turned off if need be. For example, if we use this package with textareas in the future, we probably want to disable having Enter key immediately register the input. (See readme for more info about this https://www.npmjs.com/package/react-debounce-input)
**Impact:** On the facilities page, you can now input an entire number instead of typing it digit by digit, waiting for the graph on the right to update …
=> Debounce inputs to make text easier to enter

src/hooks/useScreenWidth.tsx, src/page-multi-facility/FacilityInputForm.tsx
Puts the _Save_ button in a fixed bar on the facility page so that users always know how to save and update their data.
Closes #467
=> Fix "Save" button to the bottom of facility detail page to be always visible when editing a facility

src/rt-comparison-chart/RtComparisonChart.tsx
Set the Rate of Spread panel chart's x-axis from 0-5 for all cases except when the Rt range is greater than or equal to 4, then set it to the max plus 1. 
@macfarlandian While I was testing this I tried to add historical cases to a facility to try and get an Rt calculation that went beyond 4 and while doing it I noticed this error whenever my cases number was very close to the total residents number (i.e. I put 20,000 cases for 25,000 residents) Just wanted to check if this is an expected error or if I should open an issue for it:
Closes #386 
=> Set Rate of Spread panel chart range to 0-5

src/impact-dashboard/CurveChart.tsx, src/page-response-impact/ProjectionCharts.tsx
This PR sets the y-axis range on both current and original curve charts to be the highest value from either chart so that they match. 
Closes #397 
=> Align y-axis max value for original and current curve charts

src/impact-dashboard/FacilityInformation.tsx
IS (Changed input label to add `Cumulative`):
Still working on another part, so committing separately
Part of #372, Google doc
=> Merlin UI polish: Change copy for clarity

src/design-system/EditInPlace.tsx
This uses the `valueIsInvalid` check to initially set the `editing` state for the input component. If the value is empty and is required, then it will be `editing=true`, and it will change to `editing=false` only when onBlur or onEnterPress are called and the value is valid. 
Closes  #371
=> Set facility name input to editing until input blurs or Enter key is pressed

backend/python-functions/realtime_rt.py, backend/python-functions/test.py
The Rt function requires cumulative case counts to produce a valid output; currently it does not validate the inputs for this requirement, and it behaves inconsistently when it is violated. This adds a check for obvious violations (decreases over time) and responds with an error when they are found.
Closes #494 
=> Verify cases counts increase monotonically in Rt function

backend/python-functions/helpers.py, backend/python-functions/realtime_rt.py, src/infection-model/rt.tsx, src/page-multi-facility/FacilityRowRtValuePill.tsx, src/page-multi-facility/SystemSummary.tsx, src/page-multi-facility/projectionCurveHooks.tsx, src/page-multi-facility/types.tsx, src/page-response-impact/RtSummaryStats.tsx, src/rt-comparison-chart/RtComparisonChart.tsx, src/rt-comparison-chart/RtComparisonChartContainer.tsx, src/rt-timeseries/RtTimeseriesContainer.tsx
Makes Rt failures less opaque, with a combination of backend and frontend changes that support more useful error messaging (something we wanted but deferred in the initial Rt release): 
1. Make Python logging more reliable (with traceable Execution Ids and exception logging) so we can respond with a cleaner error message suitable for UI display
1. On the frontend, create an explicit Rt error object that can be propagated through the UI instead of a `null`. Handle this object everywhere that deals with Rt data (this is the bulk of the PR because we pass it around quite a bit)
1. When we have one of these error objects, include its message in any existing "error" or "unknown value" UI elements. @cawarren this is easy to either change or suppress in favor of additional design input so I …
=> Improve Rt function error handling

src/rt-timeseries/RtTimeseriesContainer.tsx
WAS:
IS no question mark icon with tooltip:
Closes N/A, noticed this when working on something else
=> Prevent tooltip from showing if not enough data

src/design-system/ModalDialog.tsx
_Partial fix for issues in IE11._ 
Problem: as is, Add Cases modal is too far down and to the right on IE11 and the rest of the page is not grayed out. This PR fixes the background color of the rest of the page. _Further work needed to close issue._
Part of #426
=> partial fix for modal background color on IE11

src/impact-dashboard/CurveChart.tsx
WAS:
IS:
Note: This fix only works on /facility, not the homepage FacilityRow. I can look more into that though, but this fix seemed worth shipping?
I'm familiar with D3 but this is my first time looking at it in the context of this app. Something weird is that even when it's a round number, the values are somewhat off e.g. in `WAS` screenshot ^^, value of 6 goes "above" the 6 tick mark. I didn't notice that when creating a chart with values like 63 and tick marks at 55, 60. I don't think the `yScale` needs to be adjusted.
Part of https://github.com/Recidiviz/covid19-dashboard/issues/372, Google doc
=> Add top margin to prevent chart peak being cut off

src/scenario-share/ScenarioShareLink.tsx, src/scenario-share/ScenarioShareModal.tsx
- Previously the app was throwing a warning because we were trying to nest a button within a button.  I've updated the button container to instead be a div.
Closes N/A
=> Avoiding Button Nesting Warning

src/design-system/InputText.tsx, src/design-system/InputTextNumeric.tsx, src/impact-dashboard/FacilityInformation.tsx
In FacilityInformation component, when inputting integers into Facility Details > Current cases or Total Population, add red highlight to cases if cases exceeds total for any row.
Closes #314
=> check cases input relative to total input in FacilityInformation form

src/database/index.tsx, src/design-system/EditInPlace.tsx, src/design-system/PopUpMenu.tsx, src/page-multi-facility/FacilityInputForm.tsx, src/rt-timeseries/RtTimeseriesContainer.tsx
This adds a `Duplicate` option in the popup menu for the facility input page. It saves a new facility with all of the current inputs copied over (and no historical / version data), and sets the facility name to be `Copy of "facility name"`. I also added a toast for when the page is finished re-rendering. 
I needed to add a `useEffect` to "refresh" the internal state of the `facility` for the `RtTimeseriesContainer` component and the `EditInPlace` which is used for the name and description. This is because updating the `FacilityContext` does not actually re-render all of the children components and the internal state of `facility` stays the same.  
Closes #204 
=> Add functionality to duplicate a facility

src/database/index.tsx, src/impact-dashboard/EpidemicModelContext.tsx, src/infection-model/__tests__/validateCumulativeCases.test.tsx, src/infection-model/validators.tsx
Detects cases where we have same-day but unequal timestamps among fetched model versions and re-sorts the versions to prepare them for our uniqueness-by-day filter. (Not every facility necessarily has this problem, so we skip the extra work for them.)
I also updated `saveFacility` to normalize all `observedAt` timestamps to the start of the day, which hopefully will avoid introducing this problem for new facilities. Patching the existing data is potentially tricky though, due to access and timezone issues, so I'm not actually doing this here for the moment. (We might want to actually consider changing the underlying datatype as part of that so it's kind of a larger conversation.)
There was also a bug in the recently merged historical case validation that I encountered during this work — …
=> Fix sorting/uniqueness error in model versions

src/impact-dashboard/CurveChart.tsx
Add top margin to d3 charts on / 
* Will prevent chart from being cut off, was previously fixed on /facility
WAS:
IS:
Closes part of https://github.com/Recidiviz/covid19-dashboard/issues/372, Google doc
=> Prevent chart peak from being cut off on home route 

src/design-system/InputTextNumeric.tsx
Bug was: If deleted existing value and entered "7" in "Bunk-style housing" % field, number would display with several decimals e.g. "7.000000001"
WAS:
IS:
cc @macfarlandian I was greatly overcomplicating this before 🤦‍♀️
Closes part of https://github.com/Recidiviz/covid19-dashboard/issues/372, Google doc
=> Merlin UI polish: Fix bug in % input

src/page-multi-facility/FacilityRowRtValuePill.tsx
Changed formatting of number in Rt pills to two decimal places.  (This especially causes issues for the edge case of Rt values of 0.99, 1.01 displayed in the same view.)
**Before:**
**After**
Closes #345
=> 345 - Adjust rounding of Rt pills

src/page-multi-facility/ReadOnlyScenarioBanner.tsx
Explicitly navigate to root path (Scenario Detail view) after duplicating a facility from ViewOnlyBanner button.
Note in giph, the app navigates to the newly created (copied) Scenario when duplicate button is pressed while in Facility Details view.
The original error was that clicking "duplicate" button while viewing Facility Details of a shared Scenario would leave the view on Facility Details of that Shared Scenario, so edits would rase errors.
Closes #544
=> Always navigate to root after duplicate scenario

src/hooks/useAddCasesInputs.tsx, src/page-multi-facility/AddCasesModal/index.tsx, src/page-multi-facility/HistoricalCasesChart/HistoricalAddCasesModal.tsx, src/page-multi-facility/HistoricalCasesChart/index.tsx
The bug referenced below was happening due to a discrepancy between initialization and reset of the modal, in the `useAddCasesInputs` hook. If no version matched the provided date, an effect hook would clear all the inputs. However, when the modal was closed, a reset function would set them to some default values rather than clearing them. The slightly convoluted result was that the inputs would only ever be blank the first time you opened the modal, if you didn't open it by clicking on a date in the historical cases chart that already had data (i.e. you clicked on a blank date or the "add historical data" button). 
I don't think we actually _ever_ want to clear the inputs — they should always either have either the values retrieved from the version history, or default values.
While the …
=> Simplify state management in Add Cases modal

src/design-system/InputSelect.tsx, src/locale-data-context/LocaleDataContext.tsx, src/page-weekly-snapshot/NYTDataProvider.tsx, src/page-weekly-snapshot/WeeklySnapshotPage.tsx, src/page-weekly-snapshot/index.tsx, src/pages/weekly-snapshot.tsx
This adds an admin page at `/weekly-snapshot` which loads the states and counties CSV data from the NYT github repo and displays stats for the states and counties. The "***" feature which puts those stars next to counties that have a facility in or near the county is blocked by the facility metadata workstream so is skipped for now:
@macfarlandian I used the `useAdminUser` hook at the `pages/weekly-snapshot.tsx` level, but let me know if we want to use it to whitelist users for this page at a different level. 
Closes #531 
=> [Report automation] Admin page displaying stats for states and counties

src/design-system/TextLabel.tsx, src/impact-dashboard/FacilityInformation.tsx
Conditionally hides input boxes for age vs unknown age cases and population in AddCases modal and Facility Details page.
Giph from multi-facility view:
Giph from Facility Details view:
Closes [#543 ]
=> Conditionally hide age vs unkonwn age input

src/impact-dashboard/CurveChart.tsx, src/page-multi-facility/projectionCurveHooks.tsx
This reverts commit b898ee712f5351e41193a088c133811508236ea1 re: https://recidiviz.slack.com/archives/G010VACT8F2/p1592340694050400
I need to dig into the error separately, but this would make master clean
IS: graphs appear on /impact
Closes broken seen on master 
=> Revert "#372 chart tooltip: replace People with Inmates & Staff (#564)"

src/impact-dashboard/CurveChart.tsx
Bug fix: If generated tick values = 2 and 2.5, ticks now display as 2 and 2.5, instead of previous duplicated 2 and 2
//
WAS (When the y-axis max = 3, the ticks were duplicating e.g. y-axis ticks were: 1, 1, 2, 2, 3, 3):
IS:
~~👉 Question for @macfarlandian (saw you did a lot of the graph code) or others if you have time lmk here or Slack!~~ 
~~I'm not sure if there is a better way to do this e.g. if y-axis max <= 6, use different `timeFormat` in CurveChart. But I don't see a way to access that in https://github.com/Recidiviz/covid19-dashboard/blob/master/src/rt-timeseries/RtTimeseries.tsx e.g. no max on the yExtent. Any ideas?~~ 
Closes https://github.com/Recidiviz/covid19-dashboard/issues/372, is last issue in [Google doc](https://docs.google.com/document/d/15oREP0hXoQSnzL-mMp3fTYRLyomyhs …
=> Merlin UI polish: Prevent y-axis from having dupe ticks

src/hooks/useAddCasesInputs.tsx
> Add existing data to "add historical data" modal inputs depending on if backward-or forward-looking information already exists for the selected date. The specific behavior is detailed in the corresponding issue.
Closes #523
Testing with scenario in #523:
Adding old data from 5/31:
Adding new data from 6/4:
Adding to facility without existing data:
=> Update default information for "Add Historical Data" Modal

src/database/index.tsx, src/database/type-transforms.tsx, src/database/types.tsx, src/hooks/useFacilityModelVersions.tsx, src/infection-model/rt.tsx, src/page-multi-facility/types.tsx, src/page-response-impact/responseChartData.tsx
Makes `modelVersions` a property of the `Facility` type (mirroring the database structure) and updates our database functions to always fetch model input versions alongside facility documents, and to be slightly more rigorous with type definitions when assembling and saving facilities.
In practice we will never not want this data when we are fetching facilities from the database. By storing it in the FacilitiesContext we can avoid redundant fetches from the different components that use R(t) data.
In addition to cleaning up our facility state management some more, this is important table-setting for combining user data with reference data; those merges will go much more smoothly if all this user data is already available when we are ready to join it with reference data. I have broken this …
=> always fetch model versions along with facility

backend/python-functions/realtime_rt.py, backend/python-functions/test.py
Make the Rt calculation more robust for scenarios with spotty testing that are going through an outbreak, and scenarios that are not. This includes 2 changes: removing the portion that excludes days with duplicate case counts, and smoothing the Rt result to reduce the noise caused by sporadic testing. 
I've tested this in my own research notebook locally, but have not tested this end to end in the covid app. 
Closes #608 
=> Update Rt calc to handle duplicate cases and smooth Rt result

src/page-multi-facility/FacilityChart.tsx, src/page-multi-facility/ScenarioLibraryModal.tsx
> The Scenario Library now displays the projection graph and Rt value for the first facility in a scenario instead of the Recidiviz logo. 
Closes #347
Basic testing: 
=> Enhance Data Visualization in Scenario Library with Projection Graphs

src/locale-data-context/LocaleDataContext.tsx
Something seems to have changed with published Google Sheets CSV files where they are no longer providing any CORS headers, which pretty much bricks the entire site because it prevents the Locale Data from being loaded. 
We used to use CORS Anywhere as a proxy to get around CORS issues with that fetch, but we stopped because it's not really a production service and the issues were not believed to affect end users, only developers. This seems to be a new issue that does affect end users, so this reinstitutes the CORS Anywhere proxy to fix it. 
We may still want a more permanent solution to this; consider this a stopgap for now.
none
=> fetch spreadsheet through CORS Anywhere

src/database/index.tsx
@jovergaag and I noticed this bug today while trying to share a scenario. I hadn't checked the sharing scenario functionality when adding the `referenceDataObservedAt` property, and the function `addScenarioUser` throws an error for trying to save a scenario with an undefined value. 
This fix tries to follow the pattern in `saveFacility` by using `pickBy` and removing undefined values before saving. I also thought about moving this to the `buildUpdatePayload` function instead, if people like that more let me know and I can update this. 
I was able to test this with one of my scenarios that has an undefined `referenceDataObservedAt` property. 
Closes [#XXXX]
=> Remove undefined properties before saving scenario

src/impact-dashboard/FacilityInformation.tsx, src/page-multi-facility/AddCasesModal/AddCasesModalContent.tsx
Prevent entry of duplicated age data (known ages and unknown ages) submitted at the same time.
If a user enters more than 0 in both known and unknown age inputs in a form, the save is canceled and an error message appears. Error copy: "To prevent duplicate counting, known and unknown ages cannot be entered together. Please clear either the unknown age input or all age inputs."
Gif demos:
Closes #572 
=> Prevent duplicate/conflicting age data on case entry

src/hooks/useAddCasesInputs.tsx
> In the original PR(https://github.com/Recidiviz/covid19-dashboard/pull/603) for this feature, we decided not to sort a facility's observedAt dates on the assumption that they arrived in chronological order. However, this isn't a safe assumption, which caused the logic for the pre-population to fail for some facilities. Sorting these dates should ensure that forward- and backward-looking pre-population now works per #523  
Closes #625
=> Sort Facility Observed At Dates in Add Cases Modal

src/database/index.tsx, src/design-system/Modal.tsx, src/design-system/ModalDialog.tsx, src/design-system/ModalTitle.tsx, src/page-multi-facility/MultiFacilityImpactDashboard.tsx, src/page-multi-facility/ReferenceDataModal/SyncNoUserFacilities.tsx, src/page-multi-facility/ReferenceDataModal/shared/SyncReferenceFacilitiesToggle.tsx
- Adding a toggle to globally enable or disable the syncing of Reference Facilities for a User's Baseline Scenario.
Closes #632 
=> Adding a Sync Reference Facilities Toggle

src/database/index.tsx, src/page-multi-facility/CreateBaselineScenarioPage.tsx
- Fixing the value of `useReferenceData` in the scenario defaults and instead only setting this value to true when we are creating a new Baseline Scenario.
Closes N/A
=> Only Allow Syncing of Reference Data on the Baseline Scenario

src/database/type-transforms.tsx, src/infection-model/seir.tsx, src/page-multi-facility/CreateBaselineScenarioPage.tsx, src/page-multi-facility/ScenarioSidebar.tsx, src/page-multi-facility/types.tsx
Use the recovered & death counts collected by the frontend to distribute cases for the SEIR model projection. I've updated the percentages based off Rt values that are more realistic for the facilities Zak has been working with (1.4 instead of 3.0). This shifts more of the active cases from the infectious group to the recovering groups. I've also split the "recovered" cases between our two recovered groups, and now initialize the fatalities set using the death count. I have not tested any of these changes!
Closes #607 
=> Update case distribution with active/recovered/deaths

src/impact-dashboard/ChartArea.tsx, src/impact-dashboard/CurveChart.tsx, src/infection-model/index.tsx, src/page-multi-facility/projectionCurveHooks.tsx, src/page-weekly-snapshot/FacilitySummaryRow.tsx
> Needed to shorten the duration of the projections to 3 weeks and change the fonts/colors according to the [mocks](https://www.figma.com/file/eDBdRECHwIwIo8APJlWTBN/Reports%2C-Weekly-snapshots?node-id=1%3A802) for the weekly snapshot
Testing: 
Closes #579
=> Add Facility Rt Chart to Weekly Snapshot

src/impact-dashboard/EpidemicModelContext.tsx, src/locale-data-context/LocaleDataContext.tsx, src/page-weekly-snapshot/LocaleSummary.tsx, src/page-weekly-snapshot/LocaleSummaryTable.tsx
> Add incarcerated/state cases and fatalities per capita to weekly snapshot.
test:
Closes #587
=> Add Per Capita and State Stats to Weekly Snapshot

src/hooks/useAddCasesInputs.tsx, src/impact-dashboard/EpidemicModelContext.tsx, src/page-weekly-snapshot/FacilityPage.tsx, src/page-weekly-snapshot/FacilitySummaryTable.tsx
Created a table and populated with relevant data for the facility summary. Also did a tiny bit of styling on the facility page to get it closer to the new designs, but the bulk of that work will probably need to happen in a separate PR. Open to suggestions for further condensing the logic between incarcerated/staff data!
Notes on expected behavior:
1. We don't have a notion of "weekly" data for each facility, so we calculate the delta between the current data for the facility and the most recent backwards-looking date we have for it (i.e. if a facility has data for July 1, 2, and 15, we calculate the delta between July 15 and July 2)
2. A gray arrow is expected when there is no change for any given metric
Testing: 
(decreasing cases):
Closes #578
These boxes should be checked by the …
=> Add Facility Summary Stats to Weekly Snapshot

src/page-multi-facility/ReferenceDataModal/SyncNewFacility.tsx
Fixes a bug where the SyncNewFacility modal navigates back to the homepage too soon. Checks unmappedReferenceFacilities and facilityId in an `else if` branch before navigating home. If this is approved and I'm offline, please feel free to merge!
=> Fix issue with SyncNewFacility modal navigating home too soon

src/impact-dashboard/EpidemicModelContext.tsx, src/page-weekly-snapshot/ImpactProjectionChart.tsx, src/page-weekly-snapshot/ImpactToDateTable.tsx, src/page-weekly-snapshot/LocaleSummaryTable.tsx, src/page-weekly-snapshot/projectionChartUtils.tsx, src/page-weekly-snapshot/shared/index.tsx
Adds the table stats section above the impact to date chart
cc @neeharmb  
@sychang If a calculation for one of the table numbers is negative, do we want to show that negative number, or replace it with 0?
Closes #589
=> [Report automation] Add Impact to-date table stats

src/design-system/InputSelect.tsx, src/design-system/PageColumn.tsx, src/page-weekly-snapshot/shared/index.tsx
This is the first step in generating PDF reports from the weekly snapshot page. A user can select a state and then use the browser's File > Print option to print the page. I used these print settings--but could adjust the page to any other print settings if needed (@sychang)
The next step would be to automate generating a PDF per state, @jessex and @sychang let me know if I should create a new issue for that, or keep referencing it with #644 !
Here's an example PDF:
[example_AL.pdf](https://github.com/Recidiviz/covid19-dashboard/files/4985431/example_AL.pdf)
Closes #644
=> Format page for printing to PDF

src/impact-dashboard/CurveChart.tsx, src/impact-dashboard/CurveChartContainer.tsx, src/page-multi-facility/FacilityRow.tsx, src/page-multi-facility/MultiFacilityImpactDashboard.tsx, src/page-multi-facility/projectionCurveHooks.tsx
> "Hey kids, ~~spelling~~ memoizing is fun!" --Taylor Swift at some point, probably
Changes in this PR:
1. Switch `useState` + `useEffect` patterns to `useMemo`: The expensive function `buildCurves` has been called every time the main page re-rendered, and the result has been thrown away. Switching to `useMemo` caches the results of the last call and prevents the function from being called again if the dependencies haven't changed.
2. Make tooltips optional for projection graphs on the main page: I was noticing a spike in browser memory usage when hovering over projection graphs and decided to make adding tooltips an optional parameter. This seems to have reduced memory consumption and I synced with @sychang that they are not necessary to have on the main page. This parameter can also be …
=> Performance Improvements - Part One

src/impact-dashboard/CurveChart.tsx, src/page-weekly-snapshot/FacilityPage.tsx, src/page-weekly-snapshot/FacilityProjectionChart.tsx, src/page-weekly-snapshot/FacilitySummaryTable.tsx, src/page-weekly-snapshot/ImpactProjectionChart.tsx, src/page-weekly-snapshot/ImpactToDateTable.tsx, src/page-weekly-snapshot/LocaleStatsTable.tsx, src/page-weekly-snapshot/LocaleSummaryTable.tsx, src/page-weekly-snapshot/SnapshotPage.tsx, src/page-weekly-snapshot/SystemWideProjectionChart.tsx, src/page-weekly-snapshot/SystemWideSummaryTable.tsx, src/page-weekly-snapshot/WeeklySnapshotPage.tsx, src/page-weekly-snapshot/projectionChartUtils.tsx, src/page-weekly-snapshot/shared/StatsTable.tsx, src/page-weekly-snapshot/shared/index.tsx, src/page-weekly-snapshot/shared/projectionChartUtils.tsx
[example_AL-2.pdf](https://github.com/Recidiviz/covid19-dashboard/files/5009402/example_AL-2.pdf)
Includes the following updates:
- P1: Update “???” to “No data” when we have no data
- P1: Add an arrow pointing toward the date of first case
- P1: Add more date labels on the x-axis, at least 5 total based on what’s straightforward to do with the graphing library. Actual number not important
- For # of facilities with rate of spread > 1, add 2 decimal points to make it “1.00”
- P1: Change x-axis labels from “day 0” to actual date (otherwise, there is no easy way to timestamp these pages in case they get separated from the rest of the report)
- P1: Update table font sizes and styles to match mocks. The numbers should be same style as in the summary stats. Aim to make it 2x as tall to take up …
=> Report Polish - Part 3

src/page-weekly-snapshot/LocaleSummaryTable.tsx
This adds logic for the ranking text on the locale summary table:
P2: Add logic to show “XXth lowest/highest” based on whether XX>25 or XX<=25. Example, 42nd lowest = 8th highest.
@sychang I added some additional logic so that:
- when rank = 50 it reads: "Highest of 50 states"
- when rank = 1 it reads: "Lowest of 50 states"
- when rank = 0: it doesn't show this text, and it replaces the 0 overall cases with "No data"
Let me know if there should be any changes to that!
Closes #170 
=> Format the ranking text based on rank > 25

src/page-weekly-snapshot/SystemWideProjectionChart.tsx, src/page-weekly-snapshot/shared/projectionChartUtils.tsx
This splits up the data for the 7 day system-wide projection chart on page 2 so that it shows incarcerated and staff data points as two lines. 
Part of #667
=> Split up incarcerated/staff data on system-wide projection chart

src/impact-dashboard/ImpactProjectionTableContainer.tsx, src/page-weekly-snapshot/FacilityPage.tsx
> We want the projections to match the web app, so we are using the standard duration of 90 days instead of 3 weeks.
Related to #667 
=> Fix Week 3 in Automated Report

src/infection-model/rt.tsx, src/page-weekly-snapshot/FacilityPage.tsx, src/page-weekly-snapshot/FacilityProjectionChart.tsx
This adds a facility's Rt value used to calculate the charts in the Estimated Impact heading if it's available. For now, if it's not available we're are not displaying anything, and @sychang mentioned adding something to the appendix about it. 
Part of #667 
=> Display est. rate of spread on facility chart when available

src/page-weekly-snapshot/ImpactProjectionChart.tsx, src/page-weekly-snapshot/shared/projectionChartUtils.tsx
This removes the projected and actual fatalities from the impact to date chart. Pending go ahead by @sychang 
Closes #667 
=> Remove fatalities from the impact to date chart

src/page-weekly-snapshot/FacilityProjectionChart.tsx
- Change the y-axis maxExtent to the maxValue in a projection--this matches the behavior in the web app. I'm not entirely sure what the rationale was behind adding 100 to the maxValue, but all the projections I've tested look good to me.
- Switch the color of the infectious and hospitalized lines--this also matches the behavior in the web app
- Change x-axis tick values to be calculated based on the current day so they are more evenly spaced per the mocks
Testing:
Closes #675 
=> [Report Automation] Projection Bugs

backend/firestore.rules, src/database/index.tsx
I didn't have a ton of luck nailing down a root cause for this issue, nor was I able to prevent it (if it is in fact caused by a network error, as we suspect, Firestore does not seem to throw a relevant error when we try to query it). But I was able to determine that we don't really need to throw an error from `getUserDocument` when this happens: 
- because we look up users by email/auth0Id rather than firestore ID, the application doesn't really care which of the duplicates it uses
- if we sort the query by `createdAt`, we can ensure that we always use the original (oldest) user document, and the presence of duplicates no longer has any effect
- now that we know which one is the original, we can just delete the rest (only if they are for our own user account) to stop them from piling up …
=> Handle duplicate users without throwing an error

backend/python-functions/data_ingest.py
Because our new datasource maps facilities to unique IDs, we no longer need to include so much redundant metadata in the cases export file, and we can look up facilities directly by ID. This changes the ingest function to reflect that (and also includes the batch management logic from #681, which I factored out for reuse).
In Firestore, you can see the results of these two new ingest functions in the `reference_facilities_dev` collection.
Closes #682 
=> Update case data ingest for BQ export

src/facilities-context/__fixtures__/mergedFacilities.tsx, src/facilities-context/__tests__/transforms.test.tsx, src/facilities-context/transforms.tsx
This fixes some broken tests against `FacilitiesContext` and also resolves the issue where a facility's `modelInputs` could be blank after creating it from reference data via the `SyncNoUserFacilities` modal.
Closes #651 
=> Don't create facilities from reference data with empty model inputs

src/database/index.tsx, src/database/type-transforms.tsx, src/facilities-context/__fixtures__/mergedFacilities.tsx, src/facilities-context/__tests__/transforms.test.tsx, src/facilities-context/transforms.tsx, src/page-multi-facility/types.tsx
Points the webapp at the real reference data collection in Firestore, and accounts for a small change in the final shape of those reference facility documents resulting from BigQuery exports (facility capacity, when present, is now a single unversioned number rather than a timeseries).
Note that if you have had shadow data enabled in your local environment, this change will break your configuration. But now that the "prepopulate data" modal has been built, you can use that to create a new mapping from your facilities to these new reference facility documents.
Closes #521, closes #683 
=> Use prod reference facilities data from Firestore

src/facilities-context/actions/index.tsx, src/facilities-context/actions/rtData.tsx, src/facilities-context/reducer.tsx, src/page-multi-facility/types.tsx
This fixes another of the performance issues that was exacerbated by shadow data, by setting a loading state for pending Rt requests. 
We had this (admittedly obscure) convention in the initial Rt implementation of explicitly mapping a facility ID to `undefined` while a request to the `calculate_rt` cloud function was pending, which let us only issue requests for facility IDs that were completely unmapped when initializing a facility. All the code that supported and built on that assumption was still in place but at some point the actual mapping step must have gotten lost in translation when we moved over to the `FacilitiesContext`, which was causing large numbers of duplicate requests in [the useEffect function that initializes Rt](https://github.com/Recidiviz/covid19-dashboard/blob/ian/6 …
=> Prevent repeat Rt requests while first one is loading

src/database/index.tsx, src/facilities-context/FacilitiesContext.tsx, src/page-multi-facility/ReferenceDataModal/SyncNewReferenceData.tsx, src/page-multi-facility/ReferenceDataModal/SyncNoUserFacilities.tsx, src/page-multi-facility/ReferenceDataModal/context/ReferenceDataModalContext.tsx, src/page-multi-facility/ReferenceDataModal/index.tsx, src/page-multi-facility/ReferenceDataModal/shared/ReferenceFacilitySelect.tsx
Some more thorough testing after the recent merges uncovered a few more bugs, addressed here: 
- the "promo version" of the sync dialog that appears on first visit for existing users was not rendering with the correct content
- the `referenceDataObservedAt` date was not getting consistently updated when closing the various sync dialogs, which could lead to duplicate dialogs being shown
- deleted facilities would sometimes reappear in the reference facility mapping, due to database and client getting out of sync (which could prevent you from re-mapping the reference facility in some cases)
- new users would get shown the "promo version" modal immediately after creating new facilities from reference data, which seemed redundant and potentially confusing
A test deployment with the Shadow …
=> Shadow data QA bugs

src/database/index.tsx, src/database/type-transforms.tsx, src/database/utils.tsx, src/page-multi-facility/ReadOnlyScenarioBanner.tsx, src/page-multi-facility/ScenarioLibraryModal.tsx
Adds a wrapper around Firestore batched writes to manage the batch size limit. This is similar to but more extensive than the Python version implemented in #686 ... there were some existing libraries on npm that partially implemented this but none of them had a solution for the server-side transformations contributing to the batch size, so they did not prevent the errors we were seeing. All of our unbounded client-side batch writes (duplication and deletion of scenarios and facilities) use this new wrapper and I verified that all still work (and where applicable, now succeed where they used to fail). 
Also added some additional error handling for duplication to prevent the additional baseline scenario creation that accompanied batch write failures.
Closes #701 
These boxes should be …
=> Duplication fails for large scenarios

backend/python-functions/realtime_rt.py, backend/python-functions/test.py
The Rt calc is breaking on the prison/jail data because there are long stretches of time when the case count does not change. The underlying Rt alg uses the change in cases to compute the change in Rt day over day, and it does not handle the 0 case delta at all. This change bumps up any 0 delta days to 1 so that the calculation can proceed. 
I have applied this change to a handful of states and it does not have a significant impact on the Rt results since 1 new case per day is not enough to double the total case count (double case count over 7 days -> Rt = 1). The original ticket said that all the Connecticut facilities were failing on the shadow data, so I also made sure that all of those facilities passed when the non-monotonic values are removed.
For reference, here are two state level …
=> Set the min cases per day to 1 so the likelihood/posterior calc works

src/infection-model/__tests__/curves.test.tsx, src/infection-model/seir.tsx
Addresses an issue where the projection would predict negative populations in some compartments if the current population for a bracket is less than its cumulative number of cases. This is not necessarily a user error, since people can exit a facility after being infected. It was observed in the wild in facilities with very small numbers (single digits) in individual age brackets.
Clamping negative numbers to zero in the initial distribution of current cases and population across departments prevents any subsequent projections from dipping below zero. However, we also have a competing assumption that the sum of all compartments will always equal the total population. Both conditions can't be true in this case; they will be off by the difference between cumulative cases and current …
=> Handle current population less than historical cases in projections

package.json, yarn.lock
Versions of `is-svg` (a transitive dependency of Gatsby via Webpack) below 4.2.2 have [a vulnerability](https://github.com/advisories/GHSA-7r28-3m3f-r2pr); because this package is only part of our build tooling, the actual risk here is negligible, but forcing an upgrade is trivial so we might as well do it. (This generates a yarn warning, but the only breaking change introduced by this version bump is a lack of support for Node 4.x, which we already don't support.)
Because the vulnerable package is not included in any runtime bundle, no deployment will be necessary to complete this patch.
Closes #713 
=> Resolve security vulnerability in is-svg

.github/workflows/lint-check.yml, .github/workflows/tests.yml
There isn't any documentation in here that references the `master` branch, but there are two CI tasks that run against it. This redirects those to `main`, which I will rename before merging this. 
(Note: Vercel deployments are currently configured to use the default git branch, but we can also explicitly reset them to "main" if that doesn't work for whatever reason. This would only affect our "prerelease" deploys from master; deployments to model.recidiviz.org from the `production` branch should be unaffected by this as they are configured separately.)
part of https://github.com/Recidiviz/recidiviz-data/issues/6688
=> update workflows for default branch

package.json, src/database/utils.tsx, yarn.lock
There was a dependabot alert for this which has mysteriously vanished, but [this advisory](https://github.com/advisories/GHSA-pp75-xfpw-37g9) is addressed by updating to the latest minor version of the Firebase SDK.
Closes #722 
=> bump minor firebase version to resolve vulnerability

package.json, yarn.lock
The Firebase SDK pins all of its sub-packages, which is annoying, but forcing a patch upgrade this vulnerability seems to work fine.
As this is part of the application bundle, we should deploy this change to fully resolve the security issue. 
Closes #725 
=> force patch upgrade of @firebase/util

package.json, yarn.lock
Resolves three transitive Gatsby dependencies to non-vulnerable versions. Necessary again due to our older version of Gatsby, which still does not really seem to be worth updating. 
Mostly these are just part of dev tooling so there's not much risk associated with them anyway, but that's not necessarily the case for `normalize-url`, so we probably do want to do a release to complete this fix. Smoke tests reveal no ill effects.
Closes #729, closes #728 
=> force upgrade three low level dependencies

backend/functions/package.json, backend/functions/yarn.lock, package.json, yarn.lock
Force-resolves a transient dependency of ESLint to a secure version in both the frontend application and JS cloud functions. (The linked alert is only connected to the backend, but the same package is in the frontend dependencies as well so it's just a matter of time before Dependabot gets around to alerting on it also.) As in other Recidiviz applications on older version of ESLint, this works fine and migration to a newer ESLint version is not worthwhile at this time. No deployment is needed to patch a live vulnerability as this package is only part of the developer tooling.
Closes #737 
=> Resolve security alert for `ansi-regex`
